// ── NAVA PEACE — Internationalization ───────────────────────────────
// 12 languages: EN FR ES PT DE AR ZH RU TH JA MY HI
// Usage: include this script, then call applyLang(detectLang())

const NAVA_TRANSLATIONS = {

  en: {
    // Common
    tagline:            'TODAY HUMANITY CHOOSE PEACE',
    nav_peace:          'PEACE',
    nav_map:            'MAP',
    nav_profile:        'PROFILE',
    nav_about:          'ABOUT',
    // Registration
    lbl_country:        'Country',
    lbl_age:            'Age',
    lbl_gender:         'Gender',
    ph_country:         'Select your country',
    ph_age:             'Enter your age',
    ph_gender:          'Select',
    gender_male:        'Male',
    gender_female:      'Female',
    gender_other:       'Other',
    gender_pns:         'Prefer not to say',
    btn_join:           'JOIN THE PEACE MAP',
    footer_note:        'BE THE CHANGE YOU WANT TO SEE IN THE WORLD',
    // Peace page
    msg_for1:           'TODAY, FOR ME,',
    msg_for2:           'FOR YOU, FOR US,',
    msg_want:           'I WANT PEACE',
    msg_for3:           'AROUND THE WORLD',
    done_thank:         'THANK YOU PEACE LOVER',
    done_sub:           'YOU HAVE CHOSEN PEACE TODAY',
    done_timer_label:   'NEXT ACTION IN',
    cnt_today_lbl:      'TODAY',
    cnt_total_lbl:      'TOTAL ACTIONS',
    // Map page
    lbl_peace_lovers:   'PEACE LOVERS',
    lbl_countries:      'COUNTRIES REPRESENTED',
    lbl_today_map:      'GLOBAL ACTIONS TODAY',
    lbl_days:           'DAYS',
    lbl_since:          'SINCE LAUNCH',
    lbl_follow:         'FOLLOW US',
    // Profile page
    profile_tagline:    'COMMUNITY PROFILE',
    section_profile:    'YOUR PROFILE',
    section_doves:      'MY DOVES',
    dove_total_lbl:     'TOTAL DOVES',
    dove_own_lbl:       'OWN\nACTIONS',
    dove_ref_lbl:       'REFERRAL\nDOVES',
    section_invite:     'INVITE FRIENDS',
    copy_btn:           'COPY',
    lbl_friends:        'FRIENDS',
    lbl_invited:        'INVITED',
    lbl_doves:          'DOVES',
    lbl_from_actions:   'FROM THEIR ACTIONS',
    section_age:        'AGE DISTRIBUTION',
    section_gender:     'GENDER DISTRIBUTION',
    edit_btn:           'EDIT',
    cancel_btn:         'CANCEL',
    save_btn:           'SAVE',
    close_btn:          'CLOSE',
    copied_lbl:         '✓ COPIED',
    popup_my_doves:     'MY DOVES',
    popup_own_lbl:      'OWN ACTIONS',
    popup_ref_lbl:      'REFERRAL',
    no_data_profile:    'VOTE FIRST TO SEE YOUR PROFILE',
    lbl_country_badge:  'COUNTRY',
    lbl_age_badge:      'AGE',
    lbl_gender_badge:   'GENDER',
    lbl_days_badge:     'DAYS',
    lbl_edit_country:   'COUNTRY (2-LETTER CODE)',
    lbl_select:         '— SELECT —',
    generating_link:    'GENERATING LINK...',
    section_identity:   'MY IDENTITY',
    pseudo_change_btn:  'CHANGE',
    pseudo_auto_tag:    'AUTO',
    pseudo_placeholder: 'Your pseudonym...',
    section_message:    'MY PEACE MESSAGE',
    msg_placeholder:    'Write your peace message...',
    share_lbl:          'Share publicly',
    msg_save_btn:       'SAVE MESSAGE',
    msg_saved_lbl:      '✓ SAVED',
    peace_msg_title:    'PEACE MESSAGES',
    no_msgs_yet:        'Be the first to share a peace message.',
    // About page
    about_tagline:      'ABOUT THE MOVEMENT',
    mission_lbl:        'Our Mission',
    mission_p1:         'NAVA PEACE is a global daily movement.\nEvery day, people from every country\nmake one simple commitment:\n\n<strong>To choose peace.</strong>',
    mission_p2:         'Our goal is to demonstrate in real time, on a living world map, that humanity chooses peace. Not as a dream. As a daily act.',
    how_lbl:            'How It Works',
    step1_title:        'Register',
    step1_desc:         'Join once. Share your country, age and gender. No account, no password, no email — your privacy is protected.',
    step2_title:        'Choose Peace Every Day',
    step2_desc:         'Return each day and press the button. Your voice is counted on the global map. Every click is a real commitment.',
    step3_title:        'Invite Friends',
    step3_desc:         'Receive a unique personal code. Share it via WhatsApp, Telegram, Instagram or SMS. Every friend who joins expands the movement.',
    step4_title:        'Earn Doves',
    step4_desc:         'Your peace impact grows daily. Earn a Dove for every day you act, and another for each day a friend you invited acts.',
    dove_lbl:           'The Dove',
    dove_score:         'Your Peace Score',
    dove_desc:          'The Dove is NAVA PEACE\'s symbol of individual impact.\nIt rewards consistency and inspires others to join.\nEvery Dove represents a real act of peace —\nyours or someone you inspired.',
    dove_per_day:       '+1 Dove\nPer Day\nYou Act',
    dove_per_friend:    '+1 Dove\nPer Friend\'s\nDaily Action',
    principles_lbl:     'Our Principles',
    p_anon_name:        'Anonymous',
    p_anon_text:        'No name, no email. We only collect your country, age and gender to understand who chooses peace.',
    p_univ_name:        'Universal',
    p_univ_text:        'Open to every human being on Earth, from every country, culture and background.',
    p_daily_name:       'Daily',
    p_daily_text:       'Peace is not a single act. Returning each day is what makes the movement real and powerful.',
    p_free_name:        'Free',
    p_free_text:        'Always free. No subscriptions, no ads, no monetization. This is a movement, not a product.',
    p_trans_name:       'Transparent',
    p_trans_text:       'All data is public and visible on the live world map. No hidden numbers, no manipulation.',
    cta_btn:            '🕊  Join the Peace Map',
    welcome_back:       'WELCOME BACK, PEACE LOVER',
    // Map popovers & streak
    personal_streak:    'YOU HAVE CHOSEN PEACE {days} DAY(S) IN A ROW',
    pop_dot_label:      'Each dot = {perDotM}M people',
    pop_people_text:    'Out of 8.2 billion people on Earth.\n\nEvery great movement\nstarts with a spark. 🕊',
    pop_of_world:       'OF THE WORLD',
    pop_countries_of:   '{count} of {total} nations',
    pop_countries_text: 'Peace knows no borders.\nEvery country that joins\nbrings us closer to a peaceful world.',
    pop_today_text:     'Peace actions taken today\nacross the globe.\n\nEach day is a new opportunity.\nEvery click is a real commitment\nto choosing peace.',
    referrals_title:    'MY REFERRALS',
    referrals_see_btn:  'SEE REFERRALS',
    referrals_empty:    'No referrals yet.\nShare your link to grow\nthe peace movement!',
  },

  fr: {
    tagline:            "AUJOURD'HUI L'HUMANITÉ CHOISIT LA PAIX",
    nav_peace:          'PAIX',
    nav_map:            'CARTE',
    nav_profile:        'PROFIL',
    nav_about:          'À PROPOS',
    lbl_country:        'Pays',
    lbl_age:            'Âge',
    lbl_gender:         'Genre',
    ph_country:         'Sélectionnez votre pays',
    ph_age:             'Entrez votre âge',
    ph_gender:          'Sélectionner',
    gender_male:        'Homme',
    gender_female:      'Femme',
    gender_other:       'Autre',
    gender_pns:         'Préfère ne pas dire',
    btn_join:           'REJOINDRE LA CARTE DE LA PAIX',
    footer_note:        'SOYEZ LE CHANGEMENT QUE VOUS VOULEZ VOIR DANS LE MONDE',
    msg_for1:           "AUJOURD'HUI, POUR MOI,",
    msg_for2:           'POUR TOI, POUR NOUS,',
    msg_want:           'JE VEUX LA PAIX',
    msg_for3:           'À TRAVERS LE MONDE',
    done_thank:         'MERCI, AMOUREUX DE LA PAIX',
    done_sub:           "TU AS CHOISI LA PAIX AUJOURD'HUI",
    done_timer_label:   'PROCHAINE ACTION DANS',
    cnt_today_lbl:      "AUJOURD'HUI",
    cnt_total_lbl:      'TOTAL DES ACTIONS',
    lbl_peace_lovers:   'AMOUREUX DE LA PAIX',
    lbl_countries:      'PAYS REPRÉSENTÉS',
    lbl_today_map:      "ACTIONS MONDIALES AUJOURD'HUI",
    lbl_days:           'JOURS',
    lbl_since:          'DEPUIS LE LANCEMENT',
    lbl_follow:         'NOUS SUIVRE',
    profile_tagline:    'PROFIL COMMUNAUTAIRE',
    section_profile:    'VOTRE PROFIL',
    section_doves:      'MES COLOMBES',
    dove_total_lbl:     'TOTAL COLOMBES',
    dove_own_lbl:       'MES\nACTIONS',
    dove_ref_lbl:       'COLOMBES\nPARRAINAGE',
    section_invite:     'INVITER DES AMIS',
    copy_btn:           'COPIER',
    lbl_friends:        'AMIS',
    lbl_invited:        'INVITÉS',
    lbl_doves:          'COLOMBES',
    lbl_from_actions:   'DE LEURS ACTIONS',
    section_age:        "DISTRIBUTION D'ÂGE",
    section_gender:     'DISTRIBUTION DU GENRE',
    edit_btn:           'MODIFIER',
    cancel_btn:         'ANNULER',
    save_btn:           'ENREGISTRER',
    close_btn:          'FERMER',
    copied_lbl:         '✓ COPIÉ',
    popup_my_doves:     'MES COLOMBES',
    popup_own_lbl:      'MES ACTIONS',
    popup_ref_lbl:      'PARRAINAGE',
    no_data_profile:    "VOTEZ D'ABORD POUR VOIR VOTRE PROFIL",
    lbl_country_badge:  'PAYS',
    lbl_age_badge:      'ÂGE',
    lbl_gender_badge:   'GENRE',
    lbl_days_badge:     'JOURS',
    lbl_edit_country:   'PAYS (CODE 2 LETTRES)',
    lbl_select:         '— SÉLECTIONNER —',
    generating_link:    'GÉNÉRATION DU LIEN...',
    section_identity:   'MON IDENTITÉ',
    pseudo_change_btn:  'CHANGER',
    pseudo_placeholder: 'Votre pseudonyme...',
    section_message:    'MON MESSAGE DE PAIX',
    msg_placeholder:    'Écrivez votre message de paix...',
    share_lbl:          'Partager publiquement',
    msg_save_btn:       'ENREGISTRER LE MESSAGE',
    msg_saved_lbl:      '✓ ENREGISTRÉ',
    peace_msg_title:    'MESSAGES DE PAIX',
    no_msgs_yet:        'Soyez le premier à partager un message de paix.',
    about_tagline:      'À PROPOS DU MOUVEMENT',
    mission_lbl:        'Notre Mission',
    mission_p1:         "NAVA PEACE est un mouvement mondial quotidien.\nChaque jour, des personnes de tous les pays\nprennent un engagement simple :\n\n<strong>Choisir la paix.</strong>",
    mission_p2:         "Notre but est de démontrer — en temps réel,\nsur une carte mondiale vivante — que l'humanité\nchoisit la paix. Pas comme un rêve.\nComme un acte quotidien.",
    how_lbl:            'Comment Ça Marche',
    step1_title:        "S'inscrire",
    step1_desc:         "Rejoignez-nous une seule fois. Indiquez votre pays, âge et genre. Aucun compte, aucun mot de passe, aucun email — votre vie privée est protégée.",
    step2_title:        'Choisir la Paix Chaque Jour',
    step2_desc:         "Revenez chaque jour et appuyez sur le bouton. Votre voix est comptée sur la carte mondiale. Chaque clic est un vrai engagement.",
    step3_title:        'Inviter des Amis',
    step3_desc:         'Recevez un code personnel unique. Partagez-le via WhatsApp, Telegram, Instagram ou SMS. Chaque ami qui rejoint élargit le mouvement.',
    step4_title:        'Gagner des Colombes',
    step4_desc:         "Votre impact pour la paix grandit chaque jour. Gagnez une Colombe pour chaque jour où vous agissez, et une autre pour chaque jour où un ami que vous avez invité agit.",
    dove_lbl:           'La Colombe',
    dove_score:         'Votre Score de Paix',
    dove_desc:          "La Colombe est le symbole d'impact de NAVA PEACE.\nElle récompense la constance et inspire les autres.\nChaque Colombe représente un vrai acte de paix —\lle vôtre ou celui de quelqu'un que vous avez inspiré.",
    dove_per_day:       '+1 Colombe\nPar Jour\nOù Vous Agissez',
    dove_per_friend:    "+1 Colombe\nPar Action\nD'un Ami",
    principles_lbl:     'Nos Principes',
    p_anon_name:        'Anonyme',
    p_anon_text:        "Pas de nom, pas d'email. Nous collectons uniquement votre pays, âge et genre pour comprendre qui choisit la paix.",
    p_univ_name:        'Universel',
    p_univ_text:        'Ouvert à chaque être humain sur Terre, de chaque pays, culture et origine.',
    p_daily_name:       'Quotidien',
    p_daily_text:       "La paix n'est pas un acte unique. Revenir chaque jour est ce qui rend le mouvement réel et puissant.",
    p_free_name:        'Gratuit',
    p_free_text:        "Toujours gratuit. Aucun abonnement, aucune publicité. C'est un mouvement, pas un produit.",
    p_trans_name:       'Transparent',
    p_trans_text:       'Toutes les données sont publiques et visibles sur la carte mondiale. Aucun chiffre caché, aucune manipulation.',
    cta_btn:            '🕊  Rejoindre la Carte de la Paix',
    welcome_back:       "BON RETOUR, AMOUREUX DE LA PAIX",
    // Popovers carte & série
    personal_streak:    "VOUS AVEZ CHOISI LA PAIX {days} JOUR(S) D'AFFILÉE",
    pop_dot_label:      'Chaque point = {perDotM}M personnes',
    pop_people_text:    "Sur 8,2 milliards de personnes sur Terre.\n\nChaque grand mouvement\ncommence par une étincelle. 🕊",
    pop_of_world:       'DU MONDE',
    pop_countries_of:   '{count} sur {total} nations',
    pop_countries_text: "La paix ne connaît pas de frontières.\nChaque pays qui rejoint le mouvement\nnous rapproche d'un monde pacifique.",
    pop_today_text:     "Actions de paix effectuées aujourd'hui\nà travers le monde.\n\nChaque jour est une nouvelle opportunité.\nChaque clic est un engagement réel\npour choisir la paix.",
    referrals_title:    'MES FILLEULS',
    referrals_see_btn:  'VOIR MES FILLEULS',
    referrals_empty:    "Aucun filleul pour l'instant.\nPartagez votre lien pour\nfaire grandir le mouvement!",
  },

  es: {
    tagline:            'HOY LA HUMANIDAD ELIGE LA PAZ',
    nav_peace:          'PAZ',
    nav_map:            'MAPA',
    nav_profile:        'PERFIL',
    nav_about:          'ACERCA',
    lbl_country:        'País',
    lbl_age:            'Edad',
    lbl_gender:         'Género',
    ph_country:         'Selecciona tu país',
    ph_age:             'Ingresa tu edad',
    ph_gender:          'Seleccionar',
    gender_male:        'Hombre',
    gender_female:      'Mujer',
    gender_other:       'Otro',
    gender_pns:         'Prefiero no decir',
    btn_join:           'UNIRSE AL MAPA DE LA PAZ',
    footer_note:        'SÉ EL CAMBIO QUE QUIERES VER EN EL MUNDO',
    msg_for1:           'HOY, POR MÍ,',
    msg_for2:           'POR TI, POR NOSOTROS,',
    msg_want:           'QUIERO PAZ',
    msg_for3:           'EN TODO EL MUNDO',
    done_thank:         'GRACIAS, AMANTE DE LA PAZ',
    done_sub:           'HAS ELEGIDO LA PAZ HOY',
    done_timer_label:   'PRÓXIMA ACCIÓN EN',
    cnt_today_lbl:      'HOY',
    cnt_total_lbl:      'ACCIONES TOTALES',
    lbl_peace_lovers:   'AMANTES DE LA PAZ',
    lbl_countries:      'PAÍSES REPRESENTADOS',
    lbl_today_map:      'ACCIONES GLOBALES HOY',
    lbl_days:           'DÍAS',
    lbl_since:          'DESDE EL LANZAMIENTO',
    lbl_follow:         'SÍGUENOS',
    profile_tagline:    'PERFIL COMUNITARIO',
    section_profile:    'TU PERFIL',
    section_doves:      'MIS PALOMAS',
    dove_total_lbl:     'TOTAL PALOMAS',
    dove_own_lbl:       'MIS\nACCIONES',
    dove_ref_lbl:       'PALOMAS\nDE REFERIDOS',
    section_invite:     'INVITAR AMIGOS',
    copy_btn:           'COPIAR',
    lbl_friends:        'AMIGOS',
    lbl_invited:        'INVITADOS',
    lbl_doves:          'PALOMAS',
    lbl_from_actions:   'DE SUS ACCIONES',
    section_age:        'DISTRIBUCIÓN DE EDAD',
    section_gender:     'DISTRIBUCIÓN DE GÉNERO',
    edit_btn:           'EDITAR',
    cancel_btn:         'CANCELAR',
    save_btn:           'GUARDAR',
    close_btn:          'CERRAR',
    copied_lbl:         '✓ COPIADO',
    popup_my_doves:     'MIS PALOMAS',
    popup_own_lbl:      'MIS ACCIONES',
    popup_ref_lbl:      'REFERIDOS',
    no_data_profile:    'VOTA PRIMERO PARA VER TU PERFIL',
    lbl_country_badge:  'PAÍS',
    lbl_age_badge:      'EDAD',
    lbl_gender_badge:   'GÉNERO',
    lbl_days_badge:     'DÍAS',
    lbl_edit_country:   'PAÍS (CÓDIGO 2 LETRAS)',
    lbl_select:         '— SELECCIONAR —',
    generating_link:    'GENERANDO ENLACE...',
    section_identity:   'MI IDENTIDAD',
    pseudo_change_btn:  'CAMBIAR',
    pseudo_placeholder: 'Tu seudónimo...',
    section_message:    'MI MENSAJE DE PAZ',
    msg_placeholder:    'Escribe tu mensaje de paz...',
    share_lbl:          'Compartir públicamente',
    msg_save_btn:       'GUARDAR MENSAJE',
    msg_saved_lbl:      '✓ GUARDADO',
    peace_msg_title:    'MENSAJES DE PAZ',
    no_msgs_yet:        'Sé el primero en compartir un mensaje de paz.',
    about_tagline:      'ACERCA DEL MOVIMIENTO',
    mission_lbl:        'Nuestra Misión',
    mission_p1:         'NAVA PEACE es un movimiento global diario.\nCada día, personas de todos los países\nasumen un compromiso simple:\n\n<strong>Elegir la paz.</strong>',
    mission_p2:         'Nuestro objetivo es demostrar — en tiempo real,\nen un mapa mundial vivo — que la humanidad\nelige la paz. No como un sueño.\nComo un acto diario.',
    how_lbl:            'Cómo Funciona',
    step1_title:        'Registrarse',
    step1_desc:         'Únete una sola vez. Comparte tu país, edad y género. Sin cuenta, sin contraseña, sin email — tu privacidad está protegida.',
    step2_title:        'Elegir la Paz Cada Día',
    step2_desc:         'Vuelve cada día y presiona el botón. Tu voz se cuenta en el mapa global. Cada clic es un compromiso real.',
    step3_title:        'Invitar Amigos',
    step3_desc:         'Recibe un código personal único. Compártelo por WhatsApp, Telegram, Instagram o SMS. Cada amigo que se une amplía el movimiento.',
    step4_title:        'Ganar Palomas',
    step4_desc:         'Tu impacto de paz crece cada día. Gana una Paloma por cada día que actúas, y otra por cada día que actúa un amigo que invitaste.',
    dove_lbl:           'La Paloma',
    dove_score:         'Tu Puntuación de Paz',
    dove_desc:          'La Paloma es el símbolo de impacto de NAVA PEACE.\nPremia la constancia e inspira a otros a unirse.\nCada Paloma representa un acto real de paz —\nel tuyo o el de alguien que inspiraste.',
    dove_per_day:       '+1 Paloma\nPor Día\nQue Actúas',
    dove_per_friend:    '+1 Paloma\nPor Acción\nDe Un Amigo',
    principles_lbl:     'Nuestros Principios',
    p_anon_name:        'Anónimo',
    p_anon_text:        'Sin nombre, sin email. Solo recogemos tu país, edad y género para entender quién elige la paz.',
    p_univ_name:        'Universal',
    p_univ_text:        'Abierto a todo ser humano en la Tierra, de cualquier país, cultura y origen.',
    p_daily_name:       'Diario',
    p_daily_text:       'La paz no es un acto único. Volver cada día es lo que hace que el movimiento sea real y poderoso.',
    p_free_name:        'Gratuito',
    p_free_text:        'Siempre gratis. Sin suscripciones, sin anuncios. Esto es un movimiento, no un producto.',
    p_trans_name:       'Transparente',
    p_trans_text:       'Todos los datos son públicos y visibles en el mapa mundial en vivo. Sin números ocultos, sin manipulación.',
    cta_btn:            '🕊  Unirse al Mapa de la Paz',
    welcome_back:       'BIENVENIDO DE VUELTA, AMANTE DE LA PAZ',
    // Popovers mapa & racha
    personal_streak:    'HAS ELEGIDO LA PAZ {days} DÍA(S) SEGUIDO(S)',
    pop_dot_label:      'Cada punto = {perDotM}M personas',
    pop_people_text:    'De 8,2 mil millones de personas en la Tierra.\n\nCada gran movimiento\ncomienza con una chispa. 🕊',
    pop_of_world:       'DEL MUNDO',
    pop_countries_of:   '{count} de {total} naciones',
    pop_countries_text: 'La paz no conoce fronteras.\nCada país que se une\nnos acerca a un mundo en paz.',
    pop_today_text:     'Acciones de paz realizadas hoy\nen todo el mundo.\n\nCada día es una nueva oportunidad.\nCada clic es un compromiso real\nde elegir la paz.',
    referrals_title:    'MIS REFERIDOS',
    referrals_see_btn:  'VER REFERIDOS',
    referrals_empty:    'Sin referidos aún.\nComparte tu enlace para\nhacer crecer el movimiento.',
  },

  pt: {
    tagline:            'HOJE A HUMANIDADE ESCOLHE A PAZ',
    nav_peace:          'PAZ',
    nav_map:            'MAPA',
    nav_profile:        'PERFIL',
    nav_about:          'SOBRE',
    lbl_country:        'País',
    lbl_age:            'Idade',
    lbl_gender:         'Gênero',
    ph_country:         'Selecione seu país',
    ph_age:             'Digite sua idade',
    ph_gender:          'Selecionar',
    gender_male:        'Masculino',
    gender_female:      'Feminino',
    gender_other:       'Outro',
    gender_pns:         'Prefiro não dizer',
    btn_join:           'ENTRAR NO MAPA DA PAZ',
    footer_note:        'SEJA A MUDANÇA QUE VOCÊ QUER VER NO MUNDO',
    msg_for1:           'HOJE, POR MIM,',
    msg_for2:           'POR VOCÊ, POR NÓS,',
    msg_want:           'EU QUERO PAZ',
    msg_for3:           'AO REDOR DO MUNDO',
    done_thank:         'OBRIGADO, AMANTE DA PAZ',
    done_sub:           'VOCÊ ESCOLHEU A PAZ HOJE',
    done_timer_label:   'PRÓXIMA AÇÃO EM',
    cnt_today_lbl:      'HOJE',
    cnt_total_lbl:      'AÇÕES TOTAIS',
    lbl_peace_lovers:   'AMANTES DA PAZ',
    lbl_countries:      'PAÍSES REPRESENTADOS',
    lbl_today_map:      'AÇÕES GLOBAIS HOJE',
    lbl_days:           'DIAS',
    lbl_since:          'DESDE O LANÇAMENTO',
    lbl_follow:         'SIGA-NOS',
    profile_tagline:    'PERFIL COMUNITÁRIO',
    section_profile:    'SEU PERFIL',
    section_doves:      'MINHAS POMBAS',
    dove_total_lbl:     'TOTAL POMBAS',
    dove_own_lbl:       'MINHAS\nAÇÕES',
    dove_ref_lbl:       'POMBAS\nDE INDICAÇÃO',
    section_invite:     'CONVIDAR AMIGOS',
    copy_btn:           'COPIAR',
    lbl_friends:        'AMIGOS',
    lbl_invited:        'CONVIDADOS',
    lbl_doves:          'POMBAS',
    lbl_from_actions:   'DE SUAS AÇÕES',
    section_age:        'DISTRIBUIÇÃO DE IDADE',
    section_gender:     'DISTRIBUIÇÃO DE GÊNERO',
    edit_btn:           'EDITAR',
    cancel_btn:         'CANCELAR',
    save_btn:           'SALVAR',
    close_btn:          'FECHAR',
    copied_lbl:         '✓ COPIADO',
    popup_my_doves:     'MINHAS POMBAS',
    popup_own_lbl:      'MINHAS AÇÕES',
    popup_ref_lbl:      'INDICAÇÃO',
    no_data_profile:    'VOTE PRIMEIRO PARA VER SEU PERFIL',
    lbl_country_badge:  'PAÍS',
    lbl_age_badge:      'IDADE',
    lbl_gender_badge:   'GÊNERO',
    lbl_days_badge:     'DIAS',
    lbl_edit_country:   'PAÍS (CÓDIGO 2 LETRAS)',
    lbl_select:         '— SELECIONAR —',
    generating_link:    'GERANDO LINK...',
    section_identity:   'MINHA IDENTIDADE',
    pseudo_change_btn:  'ALTERAR',
    pseudo_placeholder: 'Seu pseudônimo...',
    section_message:    'MEU MENSAGEM DE PAZ',
    msg_placeholder:    'Escreva sua mensagem de paz...',
    share_lbl:          'Compartilhar publicamente',
    msg_save_btn:       'SALVAR MENSAGEM',
    msg_saved_lbl:      '✓ SALVO',
    peace_msg_title:    'MENSAGENS DE PAZ',
    no_msgs_yet:        'Seja o primeiro a compartilhar uma mensagem de paz.',
    about_tagline:      'SOBRE O MOVIMENTO',
    mission_lbl:        'Nossa Missão',
    mission_p1:         'NAVA PEACE é um movimento global diário.\nCada dia, pessoas de todos os países\nassumem um compromisso simples:\n\n<strong>Escolher a paz.</strong>',
    mission_p2:         'Nosso objetivo é demonstrar — em tempo real,\nnuma carta mundial viva — que a humanidade\nescolhe a paz. Não como um sonho.\nComo um ato diário.',
    how_lbl:            'Como Funciona',
    step1_title:        'Cadastrar',
    step1_desc:         'Entre uma vez. Compartilhe seu país, idade e gênero. Sem conta, senha ou email — sua privacidade está protegida.',
    step2_title:        'Escolher a Paz Todo Dia',
    step2_desc:         'Volte cada dia e pressione o botão. Sua voz é contada no mapa global. Cada clique é um compromisso real.',
    step3_title:        'Convidar Amigos',
    step3_desc:         'Receba um código pessoal único. Compartilhe pelo WhatsApp, Telegram, Instagram ou SMS. Cada amigo que entra expande o movimento.',
    step4_title:        'Ganhar Pombas',
    step4_desc:         'Seu impacto de paz cresce todos os dias. Ganhe uma Pomba por cada dia que você age, e outra por cada dia que um amigo convidado age.',
    dove_lbl:           'A Pomba',
    dove_score:         'Sua Pontuação de Paz',
    dove_desc:          'A Pomba é o símbolo de impacto da NAVA PEACE.\nEla recompensa a constância e inspira outros a participar.\nCada Pomba representa um ato real de paz —\no seu ou de alguém que você inspirou.',
    dove_per_day:       '+1 Pomba\nPor Dia\nQue Age',
    dove_per_friend:    '+1 Pomba\nPor Ação\nDe Um Amigo',
    principles_lbl:     'Nossos Princípios',
    p_anon_name:        'Anônimo',
    p_anon_text:        'Sem nome, sem email. Coletamos apenas seu país, idade e gênero para entender quem escolhe a paz.',
    p_univ_name:        'Universal',
    p_univ_text:        'Aberto a todo ser humano na Terra, de qualquer país, cultura e origem.',
    p_daily_name:       'Diário',
    p_daily_text:       'A paz não é um ato único. Voltar cada dia é o que torna o movimento real e poderoso.',
    p_free_name:        'Gratuito',
    p_free_text:        'Sempre gratuito. Sem assinaturas, sem anúncios. Isso é um movimento, não um produto.',
    p_trans_name:       'Transparente',
    p_trans_text:       'Todos os dados são públicos e visíveis no mapa mundial ao vivo. Sem números ocultos, sem manipulação.',
    cta_btn:            '🕊  Entrar no Mapa da Paz',
    welcome_back:       'BEM-VINDO DE VOLTA, AMANTE DA PAZ',
    // Popovers mapa & sequência
    personal_streak:    'VOCÊ ESCOLHEU A PAZ {days} DIA(S) SEGUIDO(S)',
    pop_dot_label:      'Cada ponto = {perDotM}M pessoas',
    pop_people_text:    'De 8,2 bilhões de pessoas na Terra.\n\nCada grande movimento\ncomeça com uma faísca. 🕊',
    pop_of_world:       'DO MUNDO',
    pop_countries_of:   '{count} de {total} nações',
    pop_countries_text: 'A paz não conhece fronteiras.\nCada país que se une\nnos aproxima de um mundo em paz.',
    pop_today_text:     'Ações de paz realizadas hoje\nem todo o mundo.\n\nCada dia é uma nova oportunidade.\nCada clique é um compromisso real\nde escolher a paz.',
    referrals_title:    'MEUS INDICADOS',
    referrals_see_btn:  'VER INDICADOS',
    referrals_empty:    'Nenhum indicado ainda.\nCompartilhe seu link para\nfazer crescer o movimento.',
  },

  de: {
    tagline:            'HEUTE WÄHLT DIE MENSCHHEIT DEN FRIEDEN',
    nav_peace:          'FRIEDEN',
    nav_map:            'KARTE',
    nav_profile:        'PROFIL',
    nav_about:          'ÜBER UNS',
    lbl_country:        'Land',
    lbl_age:            'Alter',
    lbl_gender:         'Geschlecht',
    ph_country:         'Wähle dein Land',
    ph_age:             'Dein Alter eingeben',
    ph_gender:          'Auswählen',
    gender_male:        'Männlich',
    gender_female:      'Weiblich',
    gender_other:       'Andere',
    gender_pns:         'Keine Angabe',
    btn_join:           'DER FRIEDENSKARTE BEITRETEN',
    footer_note:        'SEI DER WANDEL, DEN DU IN DER WELT SEHEN MÖCHTEST',
    msg_for1:           'HEUTE, FÜR MICH,',
    msg_for2:           'FÜR DICH, FÜR UNS,',
    msg_want:           'ICH WILL FRIEDEN',
    msg_for3:           'AUF DER GANZEN WELT',
    done_thank:         'DANKE, FRIEDENSLIEBENDER',
    done_sub:           'DU HAST HEUTE FRIEDEN GEWÄHLT',
    done_timer_label:   'NÄCHSTE AKTION IN',
    cnt_today_lbl:      'HEUTE',
    cnt_total_lbl:      'AKTIONEN INSGESAMT',
    lbl_peace_lovers:   'FRIEDENSLIEBENDE',
    lbl_countries:      'VERTRETENE LÄNDER',
    lbl_today_map:      'GLOBALE AKTIONEN HEUTE',
    lbl_days:           'TAGE',
    lbl_since:          'SEIT DEM START',
    lbl_follow:         'FOLGE UNS',
    profile_tagline:    'GEMEINSCHAFTSPROFIL',
    section_profile:    'DEIN PROFIL',
    section_doves:      'MEINE TAUBEN',
    dove_total_lbl:     'TAUBEN GESAMT',
    dove_own_lbl:       'EIGENE\nAKTIONEN',
    dove_ref_lbl:       'TAUBEN\nEMPFEHLUNG',
    section_invite:     'FREUNDE EINLADEN',
    copy_btn:           'KOPIEREN',
    lbl_friends:        'FREUNDE',
    lbl_invited:        'EINGELADEN',
    lbl_doves:          'TAUBEN',
    lbl_from_actions:   'AUS IHREN AKTIONEN',
    section_age:        'ALTERSVERTEILUNG',
    section_gender:     'GESCHLECHTERVERTEILUNG',
    edit_btn:           'BEARBEITEN',
    cancel_btn:         'ABBRECHEN',
    save_btn:           'SPEICHERN',
    close_btn:          'SCHLIESSEN',
    copied_lbl:         '✓ KOPIERT',
    popup_my_doves:     'MEINE TAUBEN',
    popup_own_lbl:      'EIGENE AKTIONEN',
    popup_ref_lbl:      'EMPFEHLUNG',
    no_data_profile:    'ERST ABSTIMMEN UM PROFIL ZU SEHEN',
    lbl_country_badge:  'LAND',
    lbl_age_badge:      'ALTER',
    lbl_gender_badge:   'GESCHLECHT',
    lbl_days_badge:     'TAGE',
    lbl_edit_country:   'LAND (2-BUCHSTABEN-CODE)',
    lbl_select:         '— AUSWÄHLEN —',
    generating_link:    'LINK WIRD GENERIERT...',
    section_identity:   'MEINE IDENTITÄT',
    pseudo_change_btn:  'ÄNDERN',
    pseudo_placeholder: 'Dein Pseudonym...',
    section_message:    'MEINE FRIEDENSBOTSCHAFT',
    msg_placeholder:    'Schreib deine Friedensbotschaft...',
    share_lbl:          'Öffentlich teilen',
    msg_save_btn:       'BOTSCHAFT SPEICHERN',
    msg_saved_lbl:      '✓ GESPEICHERT',
    peace_msg_title:    'FRIEDENSBOTSCHAFTEN',
    no_msgs_yet:        'Sei der Erste, der eine Friedensbotschaft teilt.',
    about_tagline:      'ÜBER DIE BEWEGUNG',
    mission_lbl:        'Unsere Mission',
    mission_p1:         'NAVA PEACE ist eine globale tägliche Bewegung.\nJeden Tag treffen Menschen aus allen Ländern\neine einfache Entscheidung:\n\n<strong>Frieden zu wählen.</strong>',
    mission_p2:         'Unser Ziel ist es zu zeigen — in Echtzeit,\nauf einer lebenden Weltkarte — dass die Menschheit\nFrieden wählt. Nicht als Traum.\nAls täglichen Akt.',
    how_lbl:            'Wie Es Funktioniert',
    step1_title:        'Registrieren',
    step1_desc:         'Tritt einmal bei. Teile dein Land, Alter und Geschlecht. Kein Konto, kein Passwort, keine E-Mail — deine Privatsphäre ist geschützt.',
    step2_title:        'Täglich Frieden Wählen',
    step2_desc:         'Kehre jeden Tag zurück und drücke den Knopf. Deine Stimme wird auf der globalen Karte gezählt. Jeder Klick ist ein echtes Engagement.',
    step3_title:        'Freunde Einladen',
    step3_desc:         'Erhalte einen einzigartigen persönlichen Code. Teile ihn über WhatsApp, Telegram, Instagram oder SMS. Jeder Freund, der beitritt, erweitert die Bewegung.',
    step4_title:        'Tauben Verdienen',
    step4_desc:         'Dein Friedenseinfluss wächst täglich. Verdiene eine Taube für jeden Tag, an dem du handelst, und eine weitere für jeden Tag, an dem ein eingeladener Freund handelt.',
    dove_lbl:           'Die Taube',
    dove_score:         'Dein Friedens-Score',
    dove_desc:          'Die Taube ist das Symbol für individuellen Einfluss bei NAVA PEACE.\nSie belohnt Beständigkeit und inspiriert andere beizutreten.\nJede Taube steht für einen echten Friedensakt —\ndeinen oder den von jemandem, den du inspiriert hast.',
    dove_per_day:       '+1 Taube\nPro Tag\nDen Du Handelst',
    dove_per_friend:    '+1 Taube\nPro Aktion\nEines Freundes',
    principles_lbl:     'Unsere Prinzipien',
    p_anon_name:        'Anonym',
    p_anon_text:        'Kein Name, keine E-Mail. Wir erfassen nur dein Land, Alter und Geschlecht, um zu verstehen, wer Frieden wählt.',
    p_univ_name:        'Universal',
    p_univ_text:        'Offen für jeden Menschen auf der Erde, aus jedem Land, jeder Kultur und jedem Hintergrund.',
    p_daily_name:       'Täglich',
    p_daily_text:       'Frieden ist kein einmaliger Akt. Täglich zurückzukehren macht die Bewegung real und mächtig.',
    p_free_name:        'Kostenlos',
    p_free_text:        'Immer kostenlos. Keine Abonnements, keine Werbung. Dies ist eine Bewegung, kein Produkt.',
    p_trans_name:       'Transparent',
    p_trans_text:       'Alle Daten sind öffentlich und auf der Live-Weltkarte sichtbar. Keine versteckten Zahlen, keine Manipulation.',
    cta_btn:            '🕊  Der Friedenskarte Beitreten',
    welcome_back:       'WILLKOMMEN ZURÜCK, FRIEDENSLIEBENDER',
    // Karten-Popovers & Serie
    personal_streak:    'DU HAST {days} TAG(E) IN FOLGE FRIEDEN GEWÄHLT',
    pop_dot_label:      'Jeder Punkt = {perDotM}M Menschen',
    pop_people_text:    'Von 8,2 Milliarden Menschen auf der Erde.\n\nJede große Bewegung\nbeginnt mit einem Funken. 🕊',
    pop_of_world:       'DER WELT',
    pop_countries_of:   '{count} von {total} Nationen',
    pop_countries_text: 'Frieden kennt keine Grenzen.\nJedes Land, das beitritt,\nbringt uns einem friedlichen Welt näher.',
    pop_today_text:     'Friedensaktionen heute\nauf der ganzen Welt.\n\nJeder Tag ist eine neue Chance.\nJeder Klick ist ein echtes Bekenntnis\nzum Frieden.',
    referrals_title:    'MEINE EMPFEHLUNGEN',
    referrals_see_btn:  'EMPFEHLUNGEN SEHEN',
    referrals_empty:    'Noch keine Empfehlungen.\nTeile deinen Link um\ndie Bewegung zu vergrößern.',
  },

  ar: {
    tagline:            'اليوم تختار الإنسانية السلام',
    nav_peace:          'سلام',
    nav_map:            'خريطة',
    nav_profile:        'الملف',
    nav_about:          'حول',
    lbl_country:        'البلد',
    lbl_age:            'العمر',
    lbl_gender:         'الجنس',
    ph_country:         'اختر بلدك',
    ph_age:             'أدخل عمرك',
    ph_gender:          'اختر',
    gender_male:        'ذكر',
    gender_female:      'أنثى',
    gender_other:       'آخر',
    gender_pns:         'أفضل عدم الإفصاح',
    btn_join:           'انضم إلى خريطة السلام',
    footer_note:        'كن التغيير الذي تريد أن تراه في العالم',
    msg_for1:           'اليوم، من أجلي،',
    msg_for2:           'من أجلك، من أجلنا،',
    msg_want:           'أريد السلام',
    msg_for3:           'في كل أنحاء العالم',
    done_thank:         'شكراً، يا محب السلام',
    done_sub:           'لقد اخترت السلام اليوم',
    done_timer_label:   'الإجراء التالي في',
    cnt_today_lbl:      'اليوم',
    cnt_total_lbl:      'إجمالي الإجراءات',
    lbl_peace_lovers:   'محبو السلام',
    lbl_countries:      'الدول الممثلة',
    lbl_today_map:      'الإجراءات العالمية اليوم',
    lbl_days:           'أيام',
    lbl_since:          'منذ الإطلاق',
    lbl_follow:         'تابعونا',
    profile_tagline:    'الملف الشخصي',
    section_profile:    'ملفك الشخصي',
    section_doves:      'حماماتي',
    dove_total_lbl:     'إجمالي الحمامات',
    dove_own_lbl:       'أفعالي',
    dove_ref_lbl:       'حمامات الإحالة',
    section_invite:     'دعوة الأصدقاء',
    copy_btn:           'نسخ',
    lbl_friends:        'أصدقاء',
    lbl_invited:        'مدعوون',
    lbl_doves:          'حمامات',
    lbl_from_actions:   'من أفعالهم',
    section_age:        'توزيع الأعمار',
    section_gender:     'توزيع الجنس',
    edit_btn:           'تعديل',
    cancel_btn:         'إلغاء',
    save_btn:           'حفظ',
    close_btn:          'إغلاق',
    copied_lbl:         '✓ تم النسخ',
    popup_my_doves:     'حماماتي',
    popup_own_lbl:      'أفعالي',
    popup_ref_lbl:      'إحالة',
    no_data_profile:    'صوّت أولاً لرؤية ملفك',
    lbl_country_badge:  'البلد',
    lbl_age_badge:      'العمر',
    lbl_gender_badge:   'الجنس',
    lbl_days_badge:     'أيام',
    lbl_edit_country:   'البلد (رمز حرفين)',
    lbl_select:         '— اختر —',
    generating_link:    'جارٍ إنشاء الرابط...',
    section_identity:   'هويتي',
    pseudo_change_btn:  'تغيير',
    pseudo_placeholder: 'اسمك المستعار...',
    section_message:    'رسالتي للسلام',
    msg_placeholder:    'اكتب رسالتك للسلام...',
    share_lbl:          'مشاركة علنياً',
    msg_save_btn:       'حفظ الرسالة',
    msg_saved_lbl:      '✓ تم الحفظ',
    peace_msg_title:    'رسائل السلام',
    no_msgs_yet:        'كن أول من يشارك رسالة سلام.',
    about_tagline:      'حول الحركة',
    mission_lbl:        'مهمتنا',
    mission_p1:         'NAVA PEACE حركة يومية عالمية.\nكل يوم، يتخذ أشخاص من كل دولة\nالتزامًا بسيطًا:\n\n<strong>اختيار السلام.</strong>',
    mission_p2:         'هدفنا هو إثبات — في الوقت الفعلي،\nعلى خريطة عالمية حية — أن الإنسانية\nتختار السلام. ليس كحلم.\nبل كفعل يومي.',
    how_lbl:            'كيف يعمل',
    step1_title:        'التسجيل',
    step1_desc:         'انضم مرة واحدة. شارك بلدك وعمرك وجنسك. بدون حساب أو كلمة مرور أو بريد إلكتروني — خصوصيتك محمية.',
    step2_title:        'اختر السلام كل يوم',
    step2_desc:         'عد كل يوم واضغط الزر. صوتك يُحسب على الخريطة العالمية. كل نقرة هي التزام حقيقي.',
    step3_title:        'دعوة الأصدقاء',
    step3_desc:         'احصل على رمز دعوة شخصي فريد. شاركه عبر واتساب أو تيليغرام أو انستغرام أو رسائل SMS. كل صديق ينضم يوسّع الحركة.',
    step4_title:        'اكسب الحمامات',
    step4_desc:         'تأثيرك في السلام يتنامى كل يوم. اكسب حمامة عن كل يوم تتصرف فيه، وحمامة أخرى عن كل يوم يتصرف فيه صديق دعوته.',
    dove_lbl:           'الحمامة',
    dove_score:         'نقاط سلامك',
    dove_desc:          'الحمامة هي رمز التأثير الفردي في NAVA PEACE.\nتكافئ المثابرة وتلهم الآخرين للانضمام.\nكل حمامة تمثل فعل سلام حقيقي —\nفعلك أو فعل شخص ألهمته.',
    dove_per_day:       '+1 حمامة\nعن كل يوم\nتتصرف فيه',
    dove_per_friend:    '+1 حمامة\nعن كل فعل\nلصديق',
    principles_lbl:     'مبادئنا',
    p_anon_name:        'مجهول الهوية',
    p_anon_text:        'لا اسم، لا بريد إلكتروني. نجمع فقط بلدك وعمرك وجنسك لنفهم من يختار السلام.',
    p_univ_name:        'عالمي',
    p_univ_text:        'مفتوح لكل إنسان على وجه الأرض، من كل بلد وثقافة وخلفية.',
    p_daily_name:       'يومي',
    p_daily_text:       'السلام ليس فعلاً واحداً. العودة كل يوم هو ما يجعل الحركة حقيقية وقوية.',
    p_free_name:        'مجاني',
    p_free_text:        'مجاني دائماً. لا اشتراكات، لا إعلانات. هذه حركة، وليست منتجاً.',
    p_trans_name:       'شفاف',
    p_trans_text:       'جميع البيانات عامة ومرئية على الخريطة العالمية المباشرة. لا أرقام مخفية، لا تلاعب.',
    cta_btn:            '🕊  انضم إلى خريطة السلام',
    welcome_back:       'مرحباً بعودتك، يا محب السلام',
    // نوافذ الخريطة والتسلسل
    personal_streak:    'اخترت السلام {days} يوم/أيام متتالية',
    pop_dot_label:      'كل نقطة = {perDotM}م شخص',
    pop_people_text:    'من أصل 8.2 مليار شخص على الأرض.\n\nكل حركة عظيمة\nتبدأ بشرارة. 🕊',
    pop_of_world:       'من العالم',
    pop_countries_of:   '{count} من {total} دولة',
    pop_countries_text: 'السلام لا يعرف الحدود.\nكل دولة تنضم\nتقربنا من عالم سلمي.',
    pop_today_text:     'أفعال السلام اليوم\nحول العالم.\n\nكل يوم فرصة جديدة.\nكل نقرة التزام حقيقي\nباختيار السلام.',
    referrals_title:    'إحالاتي',
    referrals_see_btn:  'عرض الإحالات',
    referrals_empty:    'لا إحالات حتى الآن.\nشارك رابطك لتنمية\nحركة السلام!',
  },

  zh: {
    tagline:            '今天，人类选择和平',
    nav_peace:          '和平',
    nav_map:            '地图',
    nav_profile:        '档案',
    nav_about:          '关于',
    lbl_country:        '国家',
    lbl_age:            '年龄',
    lbl_gender:         '性别',
    ph_country:         '选择您的国家',
    ph_age:             '输入您的年龄',
    ph_gender:          '选择',
    gender_male:        '男性',
    gender_female:      '女性',
    gender_other:       '其他',
    gender_pns:         '不愿透露',
    btn_join:           '加入和平地图',
    footer_note:        '成为你希望在世界上看到的改变',
    msg_for1:           '今天，为了我，',
    msg_for2:           '为了你，为了我们，',
    msg_want:           '我要和平',
    msg_for3:           '遍及全世界',
    done_thank:         '谢谢你，和平爱好者',
    done_sub:           '你今天选择了和平',
    done_timer_label:   '下次行动倒计时',
    cnt_today_lbl:      '今天',
    cnt_total_lbl:      '总行动次数',
    lbl_peace_lovers:   '和平爱好者',
    lbl_countries:      '代表国家',
    lbl_today_map:      '今日全球行动',
    lbl_days:           '天',
    lbl_since:          '自启动以来',
    lbl_follow:         '关注我们',
    profile_tagline:    '社区档案',
    section_profile:    '你的档案',
    section_doves:      '我的鸽子',
    dove_total_lbl:     '鸽子总数',
    dove_own_lbl:       '我的\n行动',
    dove_ref_lbl:       '推荐\n鸽子',
    section_invite:     '邀请朋友',
    copy_btn:           '复制',
    lbl_friends:        '朋友',
    lbl_invited:        '已邀请',
    lbl_doves:          '鸽子',
    lbl_from_actions:   '来自他们的行动',
    section_age:        '年龄分布',
    section_gender:     '性别分布',
    edit_btn:           '编辑',
    cancel_btn:         '取消',
    save_btn:           '保存',
    close_btn:          '关闭',
    copied_lbl:         '✓ 已复制',
    popup_my_doves:     '我的鸽子',
    popup_own_lbl:      '自己的行动',
    popup_ref_lbl:      '推荐',
    no_data_profile:    '先投票查看您的档案',
    lbl_country_badge:  '国家',
    lbl_age_badge:      '年龄',
    lbl_gender_badge:   '性别',
    lbl_days_badge:     '天',
    lbl_edit_country:   '国家（2位代码）',
    lbl_select:         '— 选择 —',
    generating_link:    '正在生成链接...',
    section_identity:   '我的身份',
    pseudo_change_btn:  '更改',
    pseudo_placeholder: '您的昵称...',
    section_message:    '我的和平信息',
    msg_placeholder:    '写下您的和平信息...',
    share_lbl:          '公开分享',
    msg_save_btn:       '保存信息',
    msg_saved_lbl:      '✓ 已保存',
    peace_msg_title:    '和平信息',
    no_msgs_yet:        '成为第一个分享和平信息的人。',
    about_tagline:      '关于运动',
    mission_lbl:        '我们的使命',
    mission_p1:         'NAVA PEACE 是一个全球日常运动。\n每天，来自每个国家的人们\n做出一个简单的承诺：\n\n<strong>选择和平。</strong>',
    mission_p2:         '我们的目标是实时证明，\n通过一张活的世界地图——人类\n选择和平。不是作为梦想，\n而是作为日常行动。',
    how_lbl:            '如何运作',
    step1_title:        '注册',
    step1_desc:         '只需注册一次。分享您的国家、年龄和性别。无需账号、密码或电子邮件——您的隐私受到保护。',
    step2_title:        '每天选择和平',
    step2_desc:         '每天回来按下按钮。您的声音在全球地图上被计数。每次点击都是真实的承诺。',
    step3_title:        '邀请朋友',
    step3_desc:         '获得唯一的个人邀请码。通过WhatsApp、Telegram、Instagram或短信分享。每位加入的朋友都扩大了运动。',
    step4_title:        '赢得鸽子',
    step4_desc:         '您的和平影响力每天增长。每天行动赢得一只鸽子，邀请的朋友每天行动也为您赢得一只鸽子。',
    dove_lbl:           '鸽子',
    dove_score:         '您的和平分数',
    dove_desc:          '鸽子是NAVA PEACE个人影响力的象征。\n它奖励坚持并激励他人加入。\n每只鸽子代表一次真实的和平行动——\n您的或您激励的人的。',
    dove_per_day:       '+1只鸽子\n每天\n您行动',
    dove_per_friend:    '+1只鸽子\n朋友每次\n日常行动',
    principles_lbl:     '我们的原则',
    p_anon_name:        '匿名',
    p_anon_text:        '无需姓名或邮箱。我们只收集您的国家、年龄和性别，以了解谁选择了和平。',
    p_univ_name:        '普世',
    p_univ_text:        '向地球上每个人类开放，来自每个国家、文化和背景。',
    p_daily_name:       '每日',
    p_daily_text:       '和平不是一次性的行动。每天回来是使运动真实而强大的关键。',
    p_free_name:        '免费',
    p_free_text:        '永远免费。没有订阅，没有广告。这是一个运动，不是产品。',
    p_trans_name:       '透明',
    p_trans_text:       '所有数据公开，可在实时世界地图上看到。没有隐藏数字，没有操纵。',
    cta_btn:            '🕊  加入和平地图',
    welcome_back:       '欢迎回来，和平爱好者',
    // 地图弹窗和连续记录
    personal_streak:    '您已连续{days}天选择和平',
    pop_dot_label:      '每个点 = {perDotM}百万人',
    pop_people_text:    '地球上82亿人中的一部分。\n\n每一个伟大运动\n都从一个火花开始。🕊',
    pop_of_world:       '全球占比',
    pop_countries_of:   '{total}个国家中的{count}个',
    pop_countries_text: '和平不知国界。\n每一个加入的国家\n都使我们更接近和平世界。',
    pop_today_text:     '今天全球的和平行动。\n\n每天都是新的机会。\n每次点击都是对\n选择和平的真实承诺。',
    referrals_title:    '我的推荐人',
    referrals_see_btn:  '查看推荐人',
    referrals_empty:    '暂无推荐人。\n分享您的链接\n以扩大和平运动！',
  },

  ru: {
    tagline:            'СЕГОДНЯ ЧЕЛОВЕЧЕСТВО ВЫБИРАЕТ МИР',
    nav_peace:          'МИР',
    nav_map:            'КАРТА',
    nav_profile:        'ПРОФИЛЬ',
    nav_about:          'О НАС',
    lbl_country:        'Страна',
    lbl_age:            'Возраст',
    lbl_gender:         'Пол',
    ph_country:         'Выберите страну',
    ph_age:             'Введите ваш возраст',
    ph_gender:          'Выбрать',
    gender_male:        'Мужской',
    gender_female:      'Женский',
    gender_other:       'Другой',
    gender_pns:         'Предпочитаю не говорить',
    btn_join:           'ПРИСОЕДИНИТЬСЯ К КАРТЕ МИРА',
    footer_note:        'БУДЬТЕ ПЕРЕМЕНАМИ, КОТОРЫЕ ВЫ ХОТИТЕ ВИДЕТЬ В МИРЕ',
    msg_for1:           'СЕГОДНЯ, ДЛЯ МЕНЯ,',
    msg_for2:           'ДЛЯ ТЕБЯ, ДЛЯ НАС,',
    msg_want:           'Я ХОЧУ МИР',
    msg_for3:           'ВО ВСЁМ МИРЕ',
    done_thank:         'СПАСИБО, ЛЮБИТЕЛЬ МИРА',
    done_sub:           'СЕГОДНЯ ВЫ ВЫБРАЛИ МИР',
    done_timer_label:   'СЛЕДУЮЩЕЕ ДЕЙСТВИЕ ЧЕРЕЗ',
    cnt_today_lbl:      'СЕГОДНЯ',
    cnt_total_lbl:      'ВСЕГО ДЕЙСТВИЙ',
    lbl_peace_lovers:   'ЛЮБИТЕЛИ МИРА',
    lbl_countries:      'ПРЕДСТАВЛЕННЫЕ СТРАНЫ',
    lbl_today_map:      'ГЛОБАЛЬНЫЕ ДЕЙСТВИЯ СЕГОДНЯ',
    lbl_days:           'ДНЕ',
    lbl_since:          'С МОМЕНТА ЗАПУСКА',
    lbl_follow:         'СЛЕДИТЕ ЗА НАМИ',
    profile_tagline:    'ПРОФИЛЬ СООБЩЕСТВА',
    section_profile:    'ВАШ ПРОФИЛЬ',
    section_doves:      'МОИ ГОЛУБИ',
    dove_total_lbl:     'ВСЕГО ГОЛУБЕЙ',
    dove_own_lbl:       'МОИ\nДЕЙСТВИЯ',
    dove_ref_lbl:       'ГОЛУБИ\nОТ ДРУЗЕЙ',
    section_invite:     'ПРИГЛАСИТЬ ДРУЗЕЙ',
    copy_btn:           'КОПИРОВАТЬ',
    lbl_friends:        'ДРУЗЬЯ',
    lbl_invited:        'ПРИГЛАШЕНЫ',
    lbl_doves:          'ГОЛУБИ',
    lbl_from_actions:   'ОТ ИХ ДЕЙСТВИЙ',
    section_age:        'РАСПРЕДЕЛЕНИЕ ПО ВОЗРАСТУ',
    section_gender:     'РАСПРЕДЕЛЕНИЕ ПО ПОЛУ',
    edit_btn:           'РЕДАКТИРОВАТЬ',
    cancel_btn:         'ОТМЕНА',
    save_btn:           'СОХРАНИТЬ',
    close_btn:          'ЗАКРЫТЬ',
    copied_lbl:         '✓ СКОПИРОВАНО',
    popup_my_doves:     'МОИ ГОЛУБИ',
    popup_own_lbl:      'МОИ ДЕЙСТВИЯ',
    popup_ref_lbl:      'РЕКОМЕНДАЦИЯ',
    no_data_profile:    'СНАЧАЛА ПРОГОЛОСУЙТЕ',
    lbl_country_badge:  'СТРАНА',
    lbl_age_badge:      'ВОЗРАСТ',
    lbl_gender_badge:   'ПОЛ',
    lbl_days_badge:     'ДНИ',
    lbl_edit_country:   'СТРАНА (2-БУКВЕННЫЙ КОД)',
    lbl_select:         '— ВЫБРАТЬ —',
    generating_link:    'ГЕНЕРАЦИЯ ССЫЛКИ...',
    section_identity:   'МОЯ ЛИЧНОСТЬ',
    pseudo_change_btn:  'ИЗМЕНИТЬ',
    pseudo_placeholder: 'Ваш псевдоним...',
    section_message:    'МОЁ ПОСЛАНИЕ МИРА',
    msg_placeholder:    'Напишите ваше послание мира...',
    share_lbl:          'Поделиться публично',
    msg_save_btn:       'СОХРАНИТЬ ПОСЛАНИЕ',
    msg_saved_lbl:      '✓ СОХРАНЕНО',
    peace_msg_title:    'ПОСЛАНИЯ МИРА',
    no_msgs_yet:        'Будьте первым, кто поделится посланием мира.',
    about_tagline:      'О ДВИЖЕНИИ',
    mission_lbl:        'Наша Миссия',
    mission_p1:         'NAVA PEACE — ежедневное глобальное движение.\nКаждый день люди из всех стран\nберут на себя простое обязательство:\n\n<strong>Выбрать мир.</strong>',
    mission_p2:         'Наша цель — доказать в реальном времени,\nна живой карте мира — что человечество\nвыбирает мир. Не как мечту.\nКак ежедневный поступок.',
    how_lbl:            'Как Это Работает',
    step1_title:        'Зарегистрироваться',
    step1_desc:         'Присоединяйтесь один раз. Укажите страну, возраст и пол. Без аккаунта, пароля и email — ваша конфиденциальность защищена.',
    step2_title:        'Выбирать Мир Каждый День',
    step2_desc:         'Возвращайтесь каждый день и нажимайте кнопку. Ваш голос учитывается на глобальной карте. Каждый клик — настоящее обязательство.',
    step3_title:        'Пригласить Друзей',
    step3_desc:         'Получите уникальный личный код. Поделитесь им через WhatsApp, Telegram, Instagram или SMS. Каждый вступивший друг расширяет движение.',
    step4_title:        'Зарабатывать Голубей',
    step4_desc:         'Ваш вклад в мир растёт ежедневно. Получайте голубя за каждый день, когда вы действуете, и ещё одного за каждый день, когда действует приглашённый вами друг.',
    dove_lbl:           'Голубь',
    dove_score:         'Ваш Счёт Мира',
    dove_desc:          'Голубь — символ личного влияния NAVA PEACE.\nОн вознаграждает постоянство и вдохновляет других.\nКаждый голубь — реальный акт мира:\nваш или того, кого вы вдохновили.',
    dove_per_day:       '+1 Голубь\nЗа Каждый\nДень Действий',
    dove_per_friend:    '+1 Голубь\nЗа Действие\nДруга',
    principles_lbl:     'Наши Принципы',
    p_anon_name:        'Анонимно',
    p_anon_text:        'Без имени и email. Мы собираем только страну, возраст и пол, чтобы понять, кто выбирает мир.',
    p_univ_name:        'Универсально',
    p_univ_text:        'Открыто для каждого человека на Земле, из любой страны, культуры и происхождения.',
    p_daily_name:       'Ежедневно',
    p_daily_text:       'Мир — не разовый поступок. Возвращаться каждый день — вот что делает движение реальным и мощным.',
    p_free_name:        'Бесплатно',
    p_free_text:        'Всегда бесплатно. Без подписок и рекламы. Это движение, а не продукт.',
    p_trans_name:       'Прозрачно',
    p_trans_text:       'Все данные публичны и видны на живой карте мира. Никаких скрытых цифр, никаких манипуляций.',
    cta_btn:            '🕊  Присоединиться к Карте Мира',
    welcome_back:       'ДОБРО ПОЖАЛОВАТЬ ОБРАТНО, ЛЮБИТЕЛЬ МИРА',
    // Всплывающие окна карты и серия
    personal_streak:    'ВЫ ВЫБИРАЕТЕ МИР {days} ДЕНЬ(ДНЕЙ) ПОДРЯД',
    pop_dot_label:      'Каждая точка = {perDotM}М человек',
    pop_people_text:    'Из 8,2 миллиарда людей на Земле.\n\nКаждое великое движение\nначинается с искры. 🕊',
    pop_of_world:       'ОТ МИРА',
    pop_countries_of:   '{count} из {total} стран',
    pop_countries_text: 'Мир не знает границ.\nКаждая страна, которая присоединяется,\nприближает нас к мирному миру.',
    pop_today_text:     'Мирные действия сегодня\nпо всему миру.\n\nКаждый день — новая возможность.\nКаждый клик — настоящее обязательство\nвыбирать мир.',
    referrals_title:    'МОИ РЕФЕРАЛЫ',
    referrals_see_btn:  'СМОТРЕТЬ РЕФЕРАЛЫ',
    referrals_empty:    'Рефералов пока нет.\nПоделитесь ссылкой\nчтобы расширить движение.',
  },

  th: {
    tagline:            'วันนี้มนุษยชาติเลือกสันติภาพ',
    nav_peace:          'สันติภาพ',
    nav_map:            'แผนที่',
    nav_profile:        'โปรไฟล์',
    nav_about:          'เกี่ยวกับ',
    lbl_country:        'ประเทศ',
    lbl_age:            'อายุ',
    lbl_gender:         'เพศ',
    ph_country:         'เลือกประเทศของคุณ',
    ph_age:             'กรอกอายุของคุณ',
    ph_gender:          'เลือก',
    gender_male:        'ชาย',
    gender_female:      'หญิง',
    gender_other:       'อื่น ๆ',
    gender_pns:         'ไม่ต้องการระบุ',
    btn_join:           'เข้าร่วมแผนที่สันติภาพ',
    footer_note:        'จงเป็นการเปลี่ยนแปลงที่คุณอยากเห็นในโลก',
    msg_for1:           'วันนี้ เพื่อฉัน',
    msg_for2:           'เพื่อเธอ เพื่อเรา',
    msg_want:           'ฉันต้องการสันติภาพ',
    msg_for3:           'ทั่วทั้งโลก',
    done_thank:         'ขอบคุณ ผู้รักสันติภาพ',
    done_sub:           'คุณได้เลือกสันติภาพวันนี้',
    done_timer_label:   'การกระทำต่อไปใน',
    cnt_today_lbl:      'วันนี้',
    cnt_total_lbl:      'การกระทำทั้งหมด',
    lbl_peace_lovers:   'ผู้รักสันติภาพ',
    lbl_countries:      'ประเทศที่เข้าร่วม',
    lbl_today_map:      'การกระทำทั่วโลกวันนี้',
    lbl_days:           'วัน',
    lbl_since:          'ตั้งแต่เริ่มต้น',
    lbl_follow:         'ติดตามเรา',
    profile_tagline:    'โปรไฟล์ชุมชน',
    section_profile:    'โปรไฟล์ของคุณ',
    section_doves:      'นกพิราบของฉัน',
    dove_total_lbl:     'นกพิราบทั้งหมด',
    dove_own_lbl:       'การกระทำ\nของฉัน',
    dove_ref_lbl:       'นกพิราบ\nจากการแนะนำ',
    section_invite:     'เชิญเพื่อน',
    copy_btn:           'คัดลอก',
    lbl_friends:        'เพื่อน',
    lbl_invited:        'ที่เชิญ',
    lbl_doves:          'นกพิราบ',
    lbl_from_actions:   'จากการกระทำของพวกเขา',
    section_age:        'การกระจายตามอายุ',
    section_gender:     'การกระจายตามเพศ',
    edit_btn:           'แก้ไข',
    cancel_btn:         'ยกเลิก',
    save_btn:           'บันทึก',
    close_btn:          'ปิด',
    copied_lbl:         '✓ คัดลอกแล้ว',
    popup_my_doves:     'นกพิราบของฉัน',
    popup_own_lbl:      'การกระทำของฉัน',
    popup_ref_lbl:      'การแนะนำ',
    no_data_profile:    'โหวตก่อนเพื่อดูโปรไฟล์ของคุณ',
    lbl_country_badge:  'ประเทศ',
    lbl_age_badge:      'อายุ',
    lbl_gender_badge:   'เพศ',
    lbl_days_badge:     'วัน',
    lbl_edit_country:   'ประเทศ (รหัส 2 ตัวอักษร)',
    lbl_select:         '— เลือก —',
    generating_link:    'กำลังสร้างลิงก์...',
    section_identity:   'ตัวตนของฉัน',
    pseudo_change_btn:  'เปลี่ยน',
    pseudo_auto_tag:    'อัตโนมัติ',
    pseudo_placeholder: 'นามแฝงของคุณ...',
    section_message:    'ข้อความสันติภาพของฉัน',
    msg_placeholder:    'เขียนข้อความสันติภาพของคุณ...',
    share_lbl:          'แบ่งปันต่อสาธารณะ',
    msg_save_btn:       'บันทึกข้อความ',
    msg_saved_lbl:      '✓ บันทึกแล้ว',
    peace_msg_title:    'ข้อความสันติภาพ',
    no_msgs_yet:        'เป็นคนแรกที่แบ่งปันข้อความสันติภาพ',
    about_tagline:      'เกี่ยวกับขบวนการ',
    mission_lbl:        'พันธกิจของเรา',
    mission_p1:         'NAVA PEACE คือขบวนการประจำวันระดับโลก\nทุกวัน ผู้คนจากทุกประเทศ\nทำคำมั่นสัญญาที่เรียบง่าย:\n\n<strong>เลือกสันติภาพ</strong>',
    mission_p2:         'เป้าหมายของเราคือการแสดงให้เห็นในเวลาจริง\nบนแผนที่โลกสด ว่ามนุษยชาติเลือกสันติภาพ\nไม่ใช่เป็นความฝัน แต่เป็นการกระทำประจำวัน',
    how_lbl:            'วิธีการทำงาน',
    step1_title:        'ลงทะเบียน',
    step1_desc:         'เข้าร่วมครั้งเดียว แบ่งปันประเทศ อายุ และเพศ ไม่ต้องมีบัญชี รหัสผ่าน หรืออีเมล — ความเป็นส่วนตัวของคุณได้รับการคุ้มครอง',
    step2_title:        'เลือกสันติภาพทุกวัน',
    step2_desc:         'กลับมาทุกวันและกดปุ่ม เสียงของคุณถูกนับบนแผนที่โลก การคลิกทุกครั้งคือคำมั่นสัญญาที่แท้จริง',
    step3_title:        'เชิญเพื่อน',
    step3_desc:         'รับรหัสส่วนตัวเฉพาะ แบ่งปันผ่าน WhatsApp, Telegram, Instagram หรือ SMS ทุกเพื่อนที่เข้าร่วมขยายขบวนการ',
    step4_title:        'รับนกพิราบ',
    step4_desc:         'ผลกระทบด้านสันติภาพของคุณเติบโตทุกวัน รับนกพิราบสำหรับทุกวันที่คุณทำ และอีกหนึ่งตัวสำหรับทุกวันที่เพื่อนที่คุณเชิญทำ',
    dove_lbl:           'นกพิราบ',
    dove_score:         'คะแนนสันติภาพของคุณ',
    dove_desc:          'นกพิราบคือสัญลักษณ์ของผลกระทบส่วนบุคคลของ NAVA PEACE\nมันรางวัลความสม่ำเสมอและสร้างแรงบันดาลใจให้ผู้อื่น\nนกพิราบทุกตัวแทนการกระทำแห่งสันติภาพที่แท้จริง\nของคุณหรือของผู้ที่คุณสร้างแรงบันดาลใจ',
    dove_per_day:       '+1 นกพิราบ\nต่อวัน\nที่คุณทำ',
    dove_per_friend:    '+1 นกพิราบ\nต่อการกระทำ\nของเพื่อน',
    principles_lbl:     'หลักการของเรา',
    p_anon_name:        'ไม่ระบุชื่อ',
    p_anon_text:        'ไม่มีชื่อ ไม่มีอีเมล เราเก็บเฉพาะประเทศ อายุ และเพศเพื่อเข้าใจว่าใครเลือกสันติภาพ',
    p_univ_name:        'สากล',
    p_univ_text:        'เปิดให้มนุษย์ทุกคนบนโลก จากทุกประเทศ วัฒนธรรม และภูมิหลัง',
    p_daily_name:       'ประจำวัน',
    p_daily_text:       'สันติภาพไม่ใช่การกระทำครั้งเดียว การกลับมาทุกวันคือสิ่งที่ทำให้ขบวนการนี้เป็นจริงและมีพลัง',
    p_free_name:        'ฟรี',
    p_free_text:        'ฟรีตลอด ไม่มีการสมัครสมาชิก ไม่มีโฆษณา นี่คือขบวนการ ไม่ใช่ผลิตภัณฑ์',
    p_trans_name:       'โปร่งใส',
    p_trans_text:       'ข้อมูลทั้งหมดเปิดเผยสาธารณะและมองเห็นได้บนแผนที่โลกสด ไม่มีตัวเลขซ่อนเร้น ไม่มีการบิดเบือน',
    cta_btn:            '🕊  เข้าร่วมแผนที่สันติภาพ',
    welcome_back:       'ยินดีต้อนรับกลับมา ผู้รักสันติภาพ',
    personal_streak:    'คุณเลือกสันติภาพมาแล้ว {days} วันติดต่อกัน',
    pop_dot_label:      'แต่ละจุด = {perDotM} ล้านคน',
    pop_people_text:    'จาก 8.2 พันล้านคนบนโลก\n\nทุกขบวนการที่ยิ่งใหญ่\nเริ่มต้นจากประกายไฟ 🕊',
    pop_of_world:       'ของโลก',
    pop_countries_of:   '{count} จาก {total} ประเทศ',
    pop_countries_text: 'สันติภาพไม่รู้จักพรมแดน\nทุกประเทศที่เข้าร่วม\nทำให้เราใกล้ชิดสู่โลกที่สงบสุขมากขึ้น',
    pop_today_text:     'การกระทำสันติภาพวันนี้\nทั่วทั้งโลก\n\nทุกวันคือโอกาสใหม่\nการคลิกทุกครั้งคือคำมั่นสัญญาที่แท้จริง\nในการเลือกสันติภาพ',
    referrals_title:    'ผู้ที่ฉันแนะนำ',
    referrals_see_btn:  'ดูการแนะนำ',
    referrals_empty:    'ยังไม่มีผู้ที่คุณแนะนำ\nแบ่งปันลิงก์ของคุณเพื่อ\nขยายขบวนการสันติภาพ',
  },

  ja: {
    tagline:            '今日、人類は平和を選ぶ',
    nav_peace:          '平和',
    nav_map:            '地図',
    nav_profile:        'プロフィール',
    nav_about:          '概要',
    lbl_country:        '国',
    lbl_age:            '年齢',
    lbl_gender:         '性別',
    ph_country:         '国を選択してください',
    ph_age:             '年齢を入力してください',
    ph_gender:          '選択',
    gender_male:        '男性',
    gender_female:      '女性',
    gender_other:       'その他',
    gender_pns:         '回答しない',
    btn_join:           '平和マップに参加する',
    footer_note:        '自分が見たいと思う変化に、あなた自身がなろう',
    msg_for1:           '今日、私のために、',
    msg_for2:           'あなたのために、私たちのために、',
    msg_want:           '平和を望む',
    msg_for3:           '世界中に',
    done_thank:         'ありがとう、平和を愛する人よ',
    done_sub:           '今日あなたは平和を選びました',
    done_timer_label:   '次のアクションまで',
    cnt_today_lbl:      '今日',
    cnt_total_lbl:      '合計アクション',
    lbl_peace_lovers:   '平和を愛する人々',
    lbl_countries:      '参加国',
    lbl_today_map:      '本日の世界的アクション',
    lbl_days:           '日',
    lbl_since:          'ローンチ以来',
    lbl_follow:         'フォローする',
    profile_tagline:    'コミュニティプロフィール',
    section_profile:    'あなたのプロフィール',
    section_doves:      '私のハト',
    dove_total_lbl:     'ハトの合計',
    dove_own_lbl:       '自分の\nアクション',
    dove_ref_lbl:       '紹介\nハト',
    section_invite:     '友達を招待する',
    copy_btn:           'コピー',
    lbl_friends:        '友達',
    lbl_invited:        '招待済み',
    lbl_doves:          'ハト',
    lbl_from_actions:   '彼らのアクションから',
    section_age:        '年齢分布',
    section_gender:     '性別分布',
    edit_btn:           '編集',
    cancel_btn:         'キャンセル',
    save_btn:           '保存',
    close_btn:          '閉じる',
    copied_lbl:         '✓ コピー済み',
    popup_my_doves:     '私のハト',
    popup_own_lbl:      '自分のアクション',
    popup_ref_lbl:      '紹介',
    no_data_profile:    'プロフィールを見るには先に投票してください',
    lbl_country_badge:  '国',
    lbl_age_badge:      '年齢',
    lbl_gender_badge:   '性別',
    lbl_days_badge:     '日数',
    lbl_edit_country:   '国（2文字コード）',
    lbl_select:         '— 選択 —',
    generating_link:    'リンクを生成中...',
    section_identity:   '私のアイデンティティ',
    pseudo_change_btn:  '変更',
    pseudo_auto_tag:    '自動',
    pseudo_placeholder: 'あなたのニックネーム...',
    section_message:    '私の平和メッセージ',
    msg_placeholder:    '平和のメッセージを書いてください...',
    share_lbl:          '公開で共有',
    msg_save_btn:       'メッセージを保存',
    msg_saved_lbl:      '✓ 保存済み',
    peace_msg_title:    '平和のメッセージ',
    no_msgs_yet:        '最初に平和のメッセージを共有してください。',
    about_tagline:      'ムーブメントについて',
    mission_lbl:        '私たちのミッション',
    mission_p1:         'NAVA PEACEは毎日のグローバルムーブメントです。\n毎日、あらゆる国の人々が\n一つのシンプルな約束をします：\n\n<strong>平和を選ぶこと。</strong>',
    mission_p2:         '私たちの目標は、リアルタイムで、\n生きた世界地図の上で、人類が平和を選んでいることを示すことです。\n夢としてではなく。日々の行動として。',
    how_lbl:            '使い方',
    step1_title:        '登録する',
    step1_desc:         '一度だけ参加。国、年齢、性別を共有するだけ。アカウント、パスワード、メール不要 — あなたのプライバシーは守られます。',
    step2_title:        '毎日平和を選ぶ',
    step2_desc:         '毎日戻ってきてボタンを押してください。あなたの声は世界地図に刻まれます。クリックのたびに本物の約束になります。',
    step3_title:        '友達を招待する',
    step3_desc:         'あなただけのコードを受け取ってください。WhatsApp、Telegram、Instagram、SMSで共有してください。参加する友達が増えるほど、ムーブメントが広がります。',
    step4_title:        'ハトを獲得する',
    step4_desc:         'あなたの平和への貢献は日々成長します。行動するたびにハトを1羽獲得し、招待した友達が行動するたびにもう1羽獲得します。',
    dove_lbl:           'ハト',
    dove_score:         'あなたの平和スコア',
    dove_desc:          'ハトはNAVA PEACEの個人的影響力のシンボルです。\n継続性を報い、他者に参加を促します。\nすべてのハトは本物の平和の行動を表しています—\nあなた自身、またはあなたが鼓舞した誰かによる。',
    dove_per_day:       '+1ハト\n1日\n行動するごとに',
    dove_per_friend:    '+1ハト\n友達の\n毎日の行動ごとに',
    principles_lbl:     '私たちの原則',
    p_anon_name:        '匿名',
    p_anon_text:        '名前もメールも不要。誰が平和を選ぶかを理解するために、国、年齢、性別のみ収集します。',
    p_univ_name:        'ユニバーサル',
    p_univ_text:        '地球上のすべての人間に開かれています。どの国、文化、背景からでも。',
    p_daily_name:       '毎日',
    p_daily_text:       '平和は一度きりの行動ではありません。毎日戻ることがムーブメントをリアルで力強くするものです。',
    p_free_name:        '無料',
    p_free_text:        '常に無料。サブスクリプションも広告もなし。これはムーブメントであり、製品ではありません。',
    p_trans_name:       '透明性',
    p_trans_text:       'すべてのデータは公開されており、リアルタイムの世界地図で確認できます。隠された数字も操作もありません。',
    cta_btn:            '🕊  平和マップに参加する',
    welcome_back:       'おかえりなさい、平和を愛する人よ',
    personal_streak:    'あなたは{days}日連続して平和を選びました',
    pop_dot_label:      'ドット1つ = {perDotM}M人',
    pop_people_text:    '地球上の82億人のうち。\n\nすべての偉大なムーブメントは\n小さな火花から始まります。🕊',
    pop_of_world:       '世界の',
    pop_countries_of:   '{total}か国中{count}か国',
    pop_countries_text: '平和は国境を知りません。\n参加する国が増えるたびに\n平和な世界に近づきます。',
    pop_today_text:     '今日の世界中の平和アクション。\n\n毎日は新しいチャンスです。\nクリックのたびに\n平和を選ぶ本物の約束になります。',
    referrals_title:    '私の紹介者',
    referrals_see_btn:  '紹介者を見る',
    referrals_empty:    'まだ紹介者がいません。\nリンクを共有して\n平和ムーブメントを広げよう！',
  },

  my: {
    tagline:            'ယနေ့ လူသားများ ငြိမ်းချမ်းရေးကို ရွေးချယ်ကြသည်',
    nav_peace:          'ငြိမ်းချမ်းရေး',
    nav_map:            'မြေပုံ',
    nav_profile:        'ပရိုဖိုင်',
    nav_about:          'အကြောင်း',
    lbl_country:        'နိုင်ငံ',
    lbl_age:            'အသက်',
    lbl_gender:         'လိင်',
    ph_country:         'သင့်နိုင်ငံကို ရွေးချယ်ပါ',
    ph_age:             'သင့်အသက်ကို ဖြည့်ပါ',
    ph_gender:          'ရွေးချယ်ပါ',
    gender_male:        'ကျား',
    gender_female:      'မ',
    gender_other:       'အခြား',
    gender_pns:         'မပြောလိုပါ',
    btn_join:           'ငြိမ်းချမ်းရေးမြေပုံသို့ ပါဝင်ပါ',
    footer_note:        'ကမ္ဘာကြီးတွင် ကိုယ်တိုင်ပြောင်းလဲခြင်းဖြင့် ကမ္ဘာကို ပြောင်းလဲပါ',
    msg_for1:           'ယနေ့ ကျွန်ုပ်အတွက်',
    msg_for2:           'သင့်အတွက် ကျွန်ုပ်တို့အတွက်',
    msg_want:           'ငြိမ်းချမ်းရေးကို လိုချင်သည်',
    msg_for3:           'တစ်ကမ္ဘာလုံးတွင်',
    done_thank:         'ကျေးဇူးတင်ပါသည်၊ ငြိမ်းချမ်းရေးချစ်သူ',
    done_sub:           'သင်သည် ယနေ့ ငြိမ်းချမ်းရေးကို ရွေးချယ်ပြီးပြီ',
    done_timer_label:   'နောက်လုပ်ဆောင်ချက်',
    cnt_today_lbl:      'ယနေ့',
    cnt_total_lbl:      'စုစုပေါင်းလုပ်ဆောင်မှုများ',
    lbl_peace_lovers:   'ငြိမ်းချမ်းရေးချစ်သူများ',
    lbl_countries:      'ပါဝင်သောနိုင်ငံများ',
    lbl_today_map:      'ယနေ့ ကမ္ဘာ့လုပ်ဆောင်မှုများ',
    lbl_days:           'ရက်',
    lbl_since:          'စတင်ချိန်မှ',
    lbl_follow:         'လိုက်နာပါ',
    profile_tagline:    'အသိုင်းအဝိုင်းပရိုဖိုင်',
    section_profile:    'သင့်ပရိုဖိုင်',
    section_doves:      'ကျွန်ုပ်၏ ချိုးများ',
    dove_total_lbl:     'ချိုးစုစုပေါင်း',
    dove_own_lbl:       'ကိုယ်ပိုင်\nလုပ်ဆောင်မှုများ',
    dove_ref_lbl:       'ရည်ညွှန်းချက်\nချိုးများ',
    section_invite:     'သူငယ်ချင်းများကို ဖိတ်ခေါ်ပါ',
    copy_btn:           'ကူးယူပါ',
    lbl_friends:        'သူငယ်ချင်းများ',
    lbl_invited:        'ဖိတ်ကြားပြီး',
    lbl_doves:          'ချိုးများ',
    lbl_from_actions:   'သူတို့၏ လုပ်ဆောင်မှုများမှ',
    section_age:        'အသက်ကဏ္ဍ',
    section_gender:     'လိင်ကဏ္ဍ',
    edit_btn:           'တည်းဖြတ်ပါ',
    cancel_btn:         'ပယ်ဖျက်ပါ',
    save_btn:           'သိမ်းဆည်းပါ',
    close_btn:          'ပိတ်ပါ',
    copied_lbl:         '✓ ကူးယူပြီး',
    popup_my_doves:     'ကျွန်ုပ်၏ ချိုးများ',
    popup_own_lbl:      'ကိုယ်ပိုင်လုပ်ဆောင်မှုများ',
    popup_ref_lbl:      'ရည်ညွှန်းချက်',
    no_data_profile:    'ပရိုဖိုင်ကြည့်ရန် အရင်မဲပေးပါ',
    lbl_country_badge:  'နိုင်ငံ',
    lbl_age_badge:      'အသက်',
    lbl_gender_badge:   'လိင်',
    lbl_days_badge:     'ရက်',
    lbl_edit_country:   'နိုင်ငံ (၂ လုံးကုဒ်)',
    lbl_select:         '— ရွေးချယ်ပါ —',
    generating_link:    'လင့်ဖန်တီးနေသည်...',
    section_identity:   'ကျွန်ုပ်၏ မိမိကိုယ်မိမိ',
    pseudo_change_btn:  'ပြောင်းလဲပါ',
    pseudo_auto_tag:    'အလိုအလျောက်',
    pseudo_placeholder: 'သင့်နာမည်ကင်ပွန်း...',
    section_message:    'ကျွန်ုပ်၏ ငြိမ်းချမ်းရေးစကား',
    msg_placeholder:    'ငြိမ်းချမ်းရေးစကားရေးပါ...',
    share_lbl:          'အများပြည်သူနှင့် မျှဝေပါ',
    msg_save_btn:       'စကားသိမ်းဆည်းပါ',
    msg_saved_lbl:      '✓ သိမ်းဆည်းပြီး',
    peace_msg_title:    'ငြိမ်းချမ်းရေးစကားများ',
    no_msgs_yet:        'ပထမဦးဆုံး ငြိမ်းချမ်းရေးစကားကို မျှဝေပါ',
    about_tagline:      'လှုပ်ရှားမှုနှင့်ပတ်သက်၍',
    mission_lbl:        'ကျွန်ုပ်တို့၏ ရည်မှန်းချက်',
    mission_p1:         'NAVA PEACE သည် နေ့စဉ် ကမ္ဘာ့လှုပ်ရှားမှုတစ်ခုဖြစ်သည်။\nနေ့တိုင်း နိုင်ငံအသီးသီးမှ လူများသည်\nရိုးရှင်းသောကတိကဝတ်တစ်ခုကို ပေးကြသည်:\n\n<strong>ငြိမ်းချမ်းရေးကို ရွေးချယ်ခြင်း</strong>',
    mission_p2:         'ကျွန်ုပ်တို့၏ ရည်ရွယ်ချက်မှာ အချိန်နှင့်တပြေးညီ\nအသက်ဝင်သော ကမ္ဘာ့မြေပုံပေါ်တွင် လူသားတို့\nငြိမ်းချမ်းရေးကို ရွေးချယ်ကြောင်း သက်သေပြရန်ဖြစ်သည်\nအိပ်မက်တစ်ခုအဖြစ်မဟုတ်ဘဲ နေ့စဉ်လုပ်ဆောင်ချက်တစ်ခုအဖြစ်',
    how_lbl:            'မည်သို့အလုပ်လုပ်သနည်း',
    step1_title:        'မှတ်ပုံတင်ပါ',
    step1_desc:         'တစ်ကြိမ်သာ ပါဝင်ပါ နိုင်ငံ၊ အသက်နှင့် လိင်ကိုသာ မျှဝေပါ အကောင့်၊ စကားဝှက် သို့မဟုတ် အီးမေးလ်မလိုအပ်ပါ — သင့်ကိုယ်ရေးကိုယ်တာ ကာကွယ်ထားပြီးဖြစ်သည်',
    step2_title:        'နေ့တိုင်း ငြိမ်းချမ်းရေးကို ရွေးချယ်ပါ',
    step2_desc:         'နေ့တိုင်း ပြန်လာ၍ ခလုတ်ကိုနှိပ်ပါ သင့်အသံကို ကမ္ဘာ့မြေပုံတွင် မှတ်တမ်းတင်သည် ကလစ်တိုင်းသည် စစ်မှန်သောကတိကဝတ်တစ်ခုဖြစ်သည်',
    step3_title:        'သူငယ်ချင်းများကို ဖိတ်ကြားပါ',
    step3_desc:         'သင်၏ ကိုယ်ပိုင်ကုဒ်ကို ရယူပါ WhatsApp, Telegram, Instagram သို့မဟုတ် SMS မှတဆင့် မျှဝေပါ ပါဝင်သော သူငယ်ချင်းတိုင်းသည် လှုပ်ရှားမှုကို ချဲ့ပါသည်',
    step4_title:        'ချိုးများ ရယူပါ',
    step4_desc:         'သင်၏ ငြိမ်းချမ်းရေးသက်ရောက်မှု နေ့တိုင်း ကြီးထွားသည် သင်လုပ်ဆောင်သောနေ့တိုင်း ချိုးတစ်ကောင် ရယူပြီး သင်ဖိတ်ကြားသောသူငယ်ချင်းများ လုပ်ဆောင်သောနေ့တိုင်း ထပ်မံ ရယူပါ',
    dove_lbl:           'ချိုး',
    dove_score:         'သင့် ငြိမ်းချမ်းရေးရမှတ်',
    dove_desc:          'ချိုးသည် NAVA PEACE ၏ ပုဂ္ဂလိကသက်ရောက်မှု၏ သင်္ကေတဖြစ်သည်\nစဉ်ဆက်မပြတ်မှုကို ဆုပေးပြီး အခြားသူများကို ဆွဲဆောင်သည်\nချိုးတိုင်းသည် စစ်မှန်သောငြိမ်းချမ်းရေးလုပ်ဆောင်ချက်ကို ကိုယ်စားပြုသည်\nသင်၏ သို့မဟုတ် သင်ဆွဲဆောင်ခဲ့သောသူ၏',
    dove_per_day:       '+ချိုး ၁ကောင်\nနေ့တိုင်း\nသင်လုပ်ဆောင်သောအခါ',
    dove_per_friend:    '+ချိုး ၁ကောင်\nသူငယ်ချင်း၏\nနေ့စဉ်လုပ်ဆောင်ချက်အတွက်',
    principles_lbl:     'ကျွန်ုပ်တို့၏ မူများ',
    p_anon_name:        'အမည်မသိ',
    p_anon_text:        'နာမည်မှ အီးမေးလ်မလိုပါ ငြိမ်းချမ်းရေးကိုဘယ်သူ ရွေးချယ်ကြောင်း နားလည်ရန် နိုင်ငံ၊ အသက်နှင့် လိင်သာ သိမ်းဆည်းသည်',
    p_univ_name:        'ကမ္ဘာလုံးဆိုင်ရာ',
    p_univ_text:        'ကမ္ဘာပေါ်ရှိ လူသားတိုင်းအတွက် ဖွင့်လှစ်ထားသည် မည်သည့်နိုင်ငံ၊ ယဉ်ကျေးမှုနှင့် နောက်ခံမှ ဆိုစေ',
    p_daily_name:       'နေ့စဉ်',
    p_daily_text:       'ငြိမ်းချမ်းရေးသည် တစ်ကြိမ်တည်းသာ လုပ်ဆောင်ချက်မဟုတ်ပါ နေ့တိုင်း ပြန်လာခြင်းသည် လှုပ်ရှားမှုကို စစ်မှန်ပြီး အင်အားကြီးမားစေသည်',
    p_free_name:        'အခမဲ့',
    p_free_text:        'အမြဲ အခမဲ့ ကြေးနမ်းသွင်းခြင်းမရှိ ကြော်ငြာမရှိ ဤသည်မှာ လှုပ်ရှားမှုဖြစ်ပြီး ထုတ်ကုန်မဟုတ်ပါ',
    p_trans_name:       'ဖောက်ပြန်မှုမရှိ',
    p_trans_text:       'ဒေတာအားလုံးကို ပွင့်လင်းမြင်သာပြီး တိုက်ရိုက်ကမ္ဘာ့မြေပုံတွင် ကြည့်ရှုနိုင်သည် ဝှက်ထားသောနံပါတ်မရှိ ကွပ်ကဲမှုမရှိ',
    cta_btn:            '🕊  ငြိမ်းချမ်းရေးမြေပုံသို့ ပါဝင်ပါ',
    welcome_back:       'ကြိုဆိုပါသည်၊ ငြိမ်းချမ်းရေးချစ်သူ',
    personal_streak:    'သင်သည် {days} ရက်ဆက်တိုက် ငြိမ်းချမ်းရေးကို ရွေးချယ်ခဲ့သည်',
    pop_dot_label:      'အစက်တစ်ခုချင်း = {perDotM}M လူ',
    pop_people_text:    'ကမ္ဘာပေါ်ရှိ ၈.၂ ဘီလီယံလူ၏ ထဲမှ\n\nကြီးမြတ်သောလှုပ်ရှားမှုတိုင်းသည်\nတစ်ပွင့်မှ စတင်သည် 🕊',
    pop_of_world:       'ကမ္ဘာ့',
    pop_countries_of:   '{total} နိုင်ငံ၏ {count} နိုင်ငံ',
    pop_countries_text: 'ငြိမ်းချမ်းရေးသည် နယ်နိမိတ်မသိ\nပါဝင်သောနိုင်ငံတိုင်း\nငြိမ်းချမ်းသောကမ္ဘာဆီ ပိုမိုနီးစပ်လာသည်',
    pop_today_text:     'ယနေ့ ကမ္ဘာတစ်ဝှမ်းတွင်\nငြိမ်းချမ်းရေးလုပ်ဆောင်မှုများ\n\nနေ့တိုင်းသည် အခွင့်အလမ်းအသစ်ဖြစ်သည်\nကလစ်တိုင်းသည် ငြိမ်းချမ်းရေးကို ရွေးချယ်ရန်\nစစ်မှန်သောကတိကဝတ်ဖြစ်သည်',
    referrals_title:    'ကျွန်ုပ်ရည်ညွှန်းသူများ',
    referrals_see_btn:  'ရည်ညွှန်းသူများ ကြည့်ပါ',
    referrals_empty:    'ရည်ညွှန်းသူ မရှိသေးပါ\nသင့်လင့်ကို မျှဝေ၍\nငြိမ်းချမ်းရေးလှုပ်ရှားမှုကို ချဲ့ပါ',
  },

  hi: {
    tagline:            'आज मानवता शांति चुनती है',
    nav_peace:          'शांति',
    nav_map:            'नक्शा',
    nav_profile:        'प्रोफ़ाइल',
    nav_about:          'हमारे बारे में',
    lbl_country:        'देश',
    lbl_age:            'आयु',
    lbl_gender:         'लिंग',
    ph_country:         'अपना देश चुनें',
    ph_age:             'अपनी आयु दर्ज करें',
    ph_gender:          'चुनें',
    gender_male:        'पुरुष',
    gender_female:      'महिला',
    gender_other:       'अन्य',
    gender_pns:         'बताना नहीं चाहते',
    btn_join:           'शांति मानचित्र से जुड़ें',
    footer_note:        'वो बदलाव बनें जो आप दुनिया में देखना चाहते हैं',
    msg_for1:           'आज, मेरे लिए,',
    msg_for2:           'तुम्हारे लिए, हम सबके लिए,',
    msg_want:           'मैं शांति चाहता हूँ',
    msg_for3:           'पूरी दुनिया में',
    done_thank:         'धन्यवाद, शांति प्रेमी',
    done_sub:           'आपने आज शांति चुनी',
    done_timer_label:   'अगली कार्रवाई में',
    cnt_today_lbl:      'आज',
    cnt_total_lbl:      'कुल कार्रवाइयाँ',
    lbl_peace_lovers:   'शांति प्रेमी',
    lbl_countries:      'प्रतिनिधित्व करने वाले देश',
    lbl_today_map:      'आज की वैश्विक कार्रवाइयाँ',
    lbl_days:           'दिन',
    lbl_since:          'लॉन्च से',
    lbl_follow:         'हमें फ़ॉलो करें',
    profile_tagline:    'समुदाय प्रोफ़ाइल',
    section_profile:    'आपकी प्रोफ़ाइल',
    section_doves:      'मेरे कबूतर',
    dove_total_lbl:     'कुल कबूतर',
    dove_own_lbl:       'अपनी\nकार्रवाइयाँ',
    dove_ref_lbl:       'रेफ़रल\nकबूतर',
    section_invite:     'दोस्तों को आमंत्रित करें',
    copy_btn:           'कॉपी करें',
    lbl_friends:        'दोस्त',
    lbl_invited:        'आमंत्रित',
    lbl_doves:          'कबूतर',
    lbl_from_actions:   'उनकी कार्रवाइयों से',
    section_age:        'आयु वितरण',
    section_gender:     'लिंग वितरण',
    edit_btn:           'संपादित करें',
    cancel_btn:         'रद्द करें',
    save_btn:           'सहेजें',
    close_btn:          'बंद करें',
    copied_lbl:         '✓ कॉपी हो गया',
    popup_my_doves:     'मेरे कबूतर',
    popup_own_lbl:      'अपनी कार्रवाइयाँ',
    popup_ref_lbl:      'रेफ़रल',
    no_data_profile:    'प्रोफ़ाइल देखने के लिए पहले वोट करें',
    lbl_country_badge:  'देश',
    lbl_age_badge:      'आयु',
    lbl_gender_badge:   'लिंग',
    lbl_days_badge:     'दिन',
    lbl_edit_country:   'देश (2-अक्षर कोड)',
    lbl_select:         '— चुनें —',
    generating_link:    'लिंक बन रहा है...',
    section_identity:   'मेरी पहचान',
    pseudo_change_btn:  'बदलें',
    pseudo_auto_tag:    'स्वचालित',
    pseudo_placeholder: 'आपका उपनाम...',
    section_message:    'मेरा शांति संदेश',
    msg_placeholder:    'अपना शांति संदेश लिखें...',
    share_lbl:          'सार्वजनिक रूप से साझा करें',
    msg_save_btn:       'संदेश सहेजें',
    msg_saved_lbl:      '✓ सहेजा गया',
    peace_msg_title:    'शांति संदेश',
    no_msgs_yet:        'शांति संदेश साझा करने वाले पहले व्यक्ति बनें।',
    about_tagline:      'आंदोलन के बारे में',
    mission_lbl:        'हमारा मिशन',
    mission_p1:         'NAVA PEACE एक वैश्विक दैनिक आंदोलन है।\nहर दिन, हर देश के लोग\nएक सरल प्रतिबद्धता करते हैं:\n\n<strong>शांति चुनना।</strong>',
    mission_p2:         'हमारा लक्ष्य वास्तविक समय में,\nएक जीवित विश्व मानचित्र पर,\nयह दिखाना है कि मानवता शांति चुनती है।\nएक सपने के रूप में नहीं। एक दैनिक कार्य के रूप में।',
    how_lbl:            'यह कैसे काम करता है',
    step1_title:        'पंजीकरण करें',
    step1_desc:         'एक बार जुड़ें। अपना देश, आयु और लिंग साझा करें। कोई खाता, पासवर्ड या ईमेल नहीं — आपकी गोपनीयता सुरक्षित है।',
    step2_title:        'हर दिन शांति चुनें',
    step2_desc:         'हर दिन वापस आएं और बटन दबाएं। आपकी आवाज़ विश्व मानचित्र पर दर्ज होती है। हर क्लिक एक वास्तविक प्रतिबद्धता है।',
    step3_title:        'दोस्तों को आमंत्रित करें',
    step3_desc:         'एक अनूठा व्यक्तिगत कोड प्राप्त करें। WhatsApp, Telegram, Instagram या SMS के माध्यम से साझा करें। जुड़ने वाला हर दोस्त आंदोलन को बढ़ाता है।',
    step4_title:        'कबूतर अर्जित करें',
    step4_desc:         'आपका शांति प्रभाव हर दिन बढ़ता है। हर उस दिन के लिए एक कबूतर कमाएं जिस दिन आप कार्य करते हैं, और एक और जिस दिन आपके द्वारा आमंत्रित मित्र कार्य करता है।',
    dove_lbl:           'कबूतर',
    dove_score:         'आपका शांति स्कोर',
    dove_desc:          'कबूतर NAVA PEACE का व्यक्तिगत प्रभाव का प्रतीक है।\nयह निरंतरता को पुरस्कृत करता है और दूसरों को प्रेरित करता है।\nहर कबूतर शांति के वास्तविक कार्य को दर्शाता है —\nआपका या उस व्यक्ति का जिसे आपने प्रेरित किया।',
    dove_per_day:       '+1 कबूतर\nप्रति दिन\nजिस दिन आप कार्य करें',
    dove_per_friend:    '+1 कबूतर\nमित्र की\nप्रत्येक दैनिक कार्रवाई पर',
    principles_lbl:     'हमारे सिद्धांत',
    p_anon_name:        'अनाम',
    p_anon_text:        'कोई नाम नहीं, कोई ईमेल नहीं। हम केवल आपका देश, आयु और लिंग एकत्र करते हैं ताकि समझ सकें कि शांति कौन चुनता है।',
    p_univ_name:        'सार्वभौमिक',
    p_univ_text:        'हर देश, संस्कृति और पृष्ठभूमि से पृथ्वी पर प्रत्येक इंसान के लिए खुला।',
    p_daily_name:       'दैनिक',
    p_daily_text:       'शांति एक बार की क्रिया नहीं है। हर दिन वापस आना ही इस आंदोलन को वास्तविक और शक्तिशाली बनाता है।',
    p_free_name:        'मुफ़्त',
    p_free_text:        'हमेशा मुफ़्त। कोई सदस्यता नहीं, कोई विज्ञापन नहीं। यह एक आंदोलन है, उत्पाद नहीं।',
    p_trans_name:       'पारदर्शी',
    p_trans_text:       'सभी डेटा सार्वजनिक है और लाइव विश्व मानचित्र पर दिखाई देता है। कोई छिपी हुई संख्या नहीं, कोई हेरफेर नहीं।',
    cta_btn:            '🕊  शांति मानचित्र से जुड़ें',
    welcome_back:       'वापस आपका स्वागत है, शांति प्रेमी',
    personal_streak:    'आपने {days} दिनों से लगातार शांति चुनी है',
    pop_dot_label:      'प्रत्येक बिंदु = {perDotM}M लोग',
    pop_people_text:    'पृथ्वी पर 8.2 अरब लोगों में से।\n\nहर महान आंदोलन\nएक चिंगारी से शुरू होता है। 🕊',
    pop_of_world:       'विश्व का',
    pop_countries_of:   '{total} देशों में से {count}',
    pop_countries_text: 'शांति कोई सीमा नहीं जानती।\nजुड़ने वाला हर देश\nहमें एक शांतिपूर्ण दुनिया के करीब लाता है।',
    pop_today_text:     'आज पूरी दुनिया में\nशांति कार्रवाइयाँ की गईं।\n\nहर दिन एक नया अवसर है।\nहर क्लिक शांति चुनने की\nएक वास्तविक प्रतिबद्धता है।',
    referrals_title:    'मेरे रेफ़रल',
    referrals_see_btn:  'रेफ़रल देखें',
    referrals_empty:    'अभी कोई रेफ़रल नहीं।\nअपना लिंक साझा करें\nआंदोलन बढ़ाने के लिए।',
  },

};

// ── Language detection & application ─────────────────────────────────

const LANG_META = {
  en: { label: 'EN', flag: '🇬🇧', dir: 'ltr' },
  fr: { label: 'FR', flag: '🇫🇷', dir: 'ltr' },
  es: { label: 'ES', flag: '🇪🇸', dir: 'ltr' },
  pt: { label: 'PT', flag: '🇧🇷', dir: 'ltr' },
  de: { label: 'DE', flag: '🇩🇪', dir: 'ltr' },
  ar: { label: 'AR', flag: '🇸🇦', dir: 'rtl' },
  zh: { label: 'ZH', flag: '🇨🇳', dir: 'ltr' },
  ru: { label: 'RU', flag: '🇷🇺', dir: 'ltr' },
  th: { label: 'TH', flag: '🇹🇭', dir: 'ltr' },
  ja: { label: 'JA', flag: '🇯🇵', dir: 'ltr' },
  my: { label: 'MY', flag: '🇲🇲', dir: 'ltr' },
  hi: { label: 'HI', flag: '🇮🇳', dir: 'ltr' },
};

function detectLang() {
  const stored = localStorage.getItem('nava_peace_lang');
  if (stored && NAVA_TRANSLATIONS[stored]) return stored;
  const browser = (navigator.language || 'en').split('-')[0].toLowerCase();
  return NAVA_TRANSLATIONS[browser] ? browser : 'en';
}

function t(key) {
  const lang = localStorage.getItem('nava_peace_lang') || 'en';
  const strings = NAVA_TRANSLATIONS[lang] || NAVA_TRANSLATIONS.en;
  return strings[key] !== undefined ? strings[key] : (NAVA_TRANSLATIONS.en[key] || key);
}

function tParam(key, params) {
  let str = t(key);
  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      str = str.replace(new RegExp('\\{' + k + '\\}', 'g'), String(v));
    });
  }
  return str;
}

function applyLang(lang) {
  if (!NAVA_TRANSLATIONS[lang]) lang = 'en';
  localStorage.setItem('nava_peace_lang', lang);
  const meta = LANG_META[lang];

  // Direction (RTL for Arabic)
  document.documentElement.dir = meta.dir;
  document.documentElement.lang = lang;

  // Apply all data-i18n text nodes
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const val = t(key);
    if (val !== undefined) el.textContent = val;
  });

  // Apply innerHTML (for text with \n line breaks)
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.getAttribute('data-i18n-html');
    const val = t(key);
    if (val !== undefined) el.innerHTML = val.replace(/\n/g, '<br>');
  });

  // Apply placeholders
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.getAttribute('data-i18n-ph');
    const val = t(key);
    if (val !== undefined) el.placeholder = val;
  });

  // Update picker badge
  document.querySelectorAll('.lang-current-label').forEach(el => {
    el.textContent = meta.flag + ' ' + meta.label;
  });

  // Close menu if open
  closeLangMenu();
}

// ── Language picker widget ────────────────────────────────────────────

function toggleLangMenu() {
  const menu = document.getElementById('lang-menu');
  if (menu) menu.classList.toggle('open');
}

function closeLangMenu() {
  const menu = document.getElementById('lang-menu');
  if (menu) menu.classList.remove('open');
}

// Close when clicking outside
document.addEventListener('click', (e) => {
  if (!e.target.closest('#lang-switcher')) closeLangMenu();
});

// ── Inject CSS for the picker (once) ─────────────────────────────────
(function injectLangCSS() {
  if (document.getElementById('lang-style')) return;
  const style = document.createElement('style');
  style.id = 'lang-style';
  style.textContent = `
    #lang-switcher {
      position: fixed;
      top: 14px;
      right: 14px;
      z-index: 500;
    }
    .lang-toggle-btn {
      background: rgba(255,255,255,0.18);
      border: 1px solid rgba(255,255,255,0.35);
      border-radius: 20px;
      color: #fff;
      font-family: 'Nasalization', Arial, sans-serif;
      font-size: 11px;
      letter-spacing: 1.5px;
      padding: 6px 13px;
      cursor: pointer;
      backdrop-filter: blur(10px);
      -webkit-backdrop-filter: blur(10px);
      transition: background 0.2s;
      white-space: nowrap;
    }
    .lang-toggle-btn:hover { background: rgba(255,255,255,0.28); }
    #lang-menu {
      display: none;
      position: absolute;
      top: calc(100% + 8px);
      right: 0;
      background: rgba(20,80,140,0.92);
      border: 1px solid rgba(255,255,255,0.3);
      border-radius: 16px;
      padding: 8px;
      min-width: 140px;
      backdrop-filter: blur(18px);
      -webkit-backdrop-filter: blur(18px);
      box-shadow: 0 8px 32px rgba(10,40,100,0.45);
    }
    #lang-menu.open { display: block; }
    .lang-opt {
      display: flex;
      align-items: center;
      gap: 8px;
      width: 100%;
      background: none;
      border: none;
      border-radius: 10px;
      color: rgba(255,255,255,0.8);
      font-family: 'Nasalization', Arial, sans-serif;
      font-size: 11px;
      letter-spacing: 1.5px;
      padding: 8px 10px;
      cursor: pointer;
      text-align: left;
      transition: background 0.15s;
    }
    .lang-opt:hover { background: rgba(255,255,255,0.12); color: #fff; }
    .lang-opt.active { color: #fff; background: rgba(255,255,255,0.15); }

    /* ── SCROLL TO TOP BUTTON ── */
    #scroll-top-btn {
      position: fixed;
      bottom: 96px;
      right: 14px;
      z-index: 400;
      width: 40px;
      height: 40px;
      border-radius: 50%;
      background: rgba(255,255,255,0.18);
      border: 1px solid rgba(255,255,255,0.35);
      color: #fff;
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      backdrop-filter: blur(10px);
      -webkit-backdrop-filter: blur(10px);
      box-shadow: 0 4px 16px rgba(10,40,100,0.2);
      opacity: 0;
      transform: translateY(10px);
      transition: opacity 0.3s ease, transform 0.3s ease, background 0.2s;
      pointer-events: none;
    }
    #scroll-top-btn.visible {
      opacity: 1;
      transform: translateY(0);
      pointer-events: auto;
    }
    #scroll-top-btn:hover { background: rgba(255,255,255,0.3); }
    #scroll-top-btn svg { width: 20px; height: 20px; fill: currentColor; }
  `;
  document.head.appendChild(style);
})();

// ── Inject picker HTML & auto-apply language ──────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  // Inject the picker widget
  const switcher = document.createElement('div');
  switcher.id = 'lang-switcher';
  const currentLang = detectLang();
  const currentMeta = LANG_META[currentLang];

  switcher.innerHTML = `
    <button class="lang-toggle-btn" onclick="toggleLangMenu()">
      <span class="lang-current-label">${currentMeta.flag} ${currentMeta.label}</span>
    </button>
    <div id="lang-menu">
      ${Object.entries(LANG_META).map(([code, m]) => `
        <button class="lang-opt${code === currentLang ? ' active' : ''}" onclick="applyLang('${code}')">
          ${m.flag} ${m.label}
        </button>`).join('')}
    </div>
  `;
  document.body.appendChild(switcher);

  // ── Scroll-to-top button (appears after 300px scroll) ────────────
  const scrollBtn = document.createElement('button');
  scrollBtn.id = 'scroll-top-btn';
  scrollBtn.setAttribute('aria-label', 'Scroll to top');
  scrollBtn.innerHTML = `<svg viewBox="0 0 24 24"><path d="M7.41 15.41L12 10.83l4.59 4.58L18 14l-6-6-6 6z"/></svg>`;
  scrollBtn.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));
  document.body.appendChild(scrollBtn);

  window.addEventListener('scroll', () => {
    scrollBtn.classList.toggle('visible', window.scrollY > 300);
  }, { passive: true });

  // Apply detected/stored language
  applyLang(currentLang);
});
